// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

type Subscriber struct {
	ID             int64
	Imsi           string
	PlmnID         string
	Opc            string
	Key            string
	SequenceNumber string
}
