package per

// Marshaler is implemented by types that can encode themselves to PER.
// Implementations are normally generated by per/cmd/pergen.
type Marshaler interface {
	MarshalPER(w *Writer, enc Encoding) error
}

// Unmarshaler is implemented by types that can decode themselves from PER.
// Implementations are normally generated by per/cmd/pergen.
type Unmarshaler interface {
	UnmarshalPER(r *Reader, enc Encoding) error
}

// MarshalerFunc is an adapter allowing ordinary functions to be used as a
// Marshaler. Used by pergen to wrap primitive encoders for open-type fields.
type MarshalerFunc func(w *Writer, enc Encoding) error

// MarshalPER calls f(w, enc).
func (f MarshalerFunc) MarshalPER(w *Writer, enc Encoding) error { return f(w, enc) }

// UnmarshalerFunc is an adapter allowing ordinary functions to be used as an
// Unmarshaler. Used by pergen to wrap primitive decoders for open-type fields.
type UnmarshalerFunc func(r *Reader, enc Encoding) error

// UnmarshalPER calls f(r, enc).
func (f UnmarshalerFunc) UnmarshalPER(r *Reader, enc Encoding) error { return f(r, enc) }

// Marshal encodes m using the given encoding. If enc is omitted, [Aligned] is
// used. The returned bytes are a copy and safe to retain.
func Marshal(m Marshaler, enc ...Encoding) ([]byte, error) {
	e := Aligned
	if len(enc) > 0 {
		e = enc[0]
	}

	w := NewWriter()
	if err := m.MarshalPER(w, e); err != nil {
		return nil, err
	}
	// A complete PER encoding is padded to an octet boundary.
	w.AlignToByte()

	return w.Bytes(), nil
}

// Unmarshal decodes b into u using the given encoding. If enc is omitted,
// [Aligned] is used. Trailing bits are not an error: after decoding, the
// reader may be byte-aligned with remaining padding bits; this matches PER
// semantics where the top-level encoding is octet-aligned and trailing
// padding may exist.
func Unmarshal(b []byte, u Unmarshaler, enc ...Encoding) error {
	e := Aligned
	if len(enc) > 0 {
		e = enc[0]
	}

	r := NewReader(b)

	return u.UnmarshalPER(r, e)
}
