CREATE TABLE IF NOT EXISTS IPPool (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    device_group_id INTEGER,
    cidr TEXT NOT NULL,
    FOREIGN KEY (device_group_id) REFERENCES device_groups(id) ON DELETE CASCADE
);