
linters:
  enable:
    - gofmt
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - typecheck
    - godox
    - goconst
    - gomodguard
    - nakedret
    - misspell
    - gofumpt
    - whitespace
    - unconvert
    - predeclared
    - noctx
    - dogsled
    - bodyclose
    - asciicheck
    - unparam
    - gci
    - stylecheck
    # - gocognit
    # - nestif
    # - wsl
