
linters:
  enable:
    - gofmt
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - typecheck
    - godox
    - goconst
    - gomodguard
    - nakedret
    - misspell
    - gofumpt
    - whitespace
    - unconvert
    - predeclared
    - noctx
    - dogsled
    - bodyclose
    - asciicheck
    - unparam
    # - stylecheck
    # - gci
    # - lll
    # - gocognit
    # - nestif
    # - wsl

  fast: true
issues:
  exclude:
  exclude-rules:
  exclude-case-sensitive: false
  include:
  new: false
  new-from-rev: ""
severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - gomnd
      severity: ignore
