apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ueransim-deployment.yaml
  - ueransim-configmap.yaml
  - ueransim-n2-nad.yaml
  - ueransim-n3-nad.yaml
configMapGenerator:
- name: network-testing-script
  files:
  - network_test.py
