// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"database/sql"
)

type SmPolicyDatum struct {
	ID   int64
	UeID string
}

type SmPolicyDnnDatum struct {
	ID                   int64
	SmPolicySnssaiDataID int64
	Dnn                  string
}

type SmPolicySnssaiDatum struct {
	ID             int64
	SmPolicyDataID int64
	SnssaiSd       string
	SnssaiSst      int64
}

type UsageMonDataScope struct {
	ID             int64
	UsageMonDataID int64
	SnssaiSd       string
	SnssaiSst      int64
	Dnn            string
}

type UsageMonDatum struct {
	ID           int64
	UeID         string
	LimitID      string
	UmLevel      string
	AllowedUsage string
	ResetTime    string
	CreatedAt    sql.NullTime
	UpdatedAt    interface{}
}
