// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sm_policy_dnn_data.sql

package sql

import (
	"context"
)

const getSmPolicyDnnDataBySnssaiId = `-- name: GetSmPolicyDnnDataBySnssaiId :many
SELECT id, sm_policy_snssai_data_id, dnn
FROM sm_policy_dnn_data
WHERE sm_policy_snssai_data_id = ?
`

func (q *Queries) GetSmPolicyDnnDataBySnssaiId(ctx context.Context, smPolicySnssaiDataID int64) ([]SmPolicyDnnDatum, error) {
	rows, err := q.db.QueryContext(ctx, getSmPolicyDnnDataBySnssaiId, smPolicySnssaiDataID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmPolicyDnnDatum
	for rows.Next() {
		var i SmPolicyDnnDatum
		if err := rows.Scan(&i.ID, &i.SmPolicySnssaiDataID, &i.Dnn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
