apiVersion: 1

datasources:
  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    url: http://ella-mimir:9009/prometheus
    isDefault: true
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://ella-loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceID":"([a-f0-9]+)"'
          name: traceID
          url: "$${__value.raw}"

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://ella-tempo:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{job="ella-core"} | traceID=`$${__trace.traceId}`'

  - name: Pyroscope
    uid: pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://ella-pyroscope:4040
    editable: true
