// SPDX-FileCopyrightText: Ella Networks Inc.
// SPDX-License-Identifier: BUSL-1.1

package ngap

import "fmt"

// ProtocolIE-ID names from TS 38.413 §9.4.7, spelled as the ASN.1
// identifiers are. IDs are unique protocol-wide.
//
// #nosec G101 -- these are 3GPP IE names, not credentials. G101 matches its
// "pw" pattern against the PWS list names, where PWS is the Public Warning
// System (TS 38.413 §8.9), and its "key" pattern against SecurityKey, which
// names the IE carrying the key, never a key value.
var protocolIENames = map[ProtocolIEID]string{
	IDAllowedNSSAI:                                "AllowedNSSAI",
	IDAMFName:                                     "AMFName",
	IDAMFOverloadResponse:                         "AMFOverloadResponse",
	IDAMFSetID:                                    "AMFSetID",
	IDAMFTNLAssociationFailedToSetupList:          "AMF-TNLAssociationFailedToSetupList",
	IDAMFTNLAssociationSetupList:                  "AMF-TNLAssociationSetupList",
	IDAMFTNLAssociationToAddList:                  "AMF-TNLAssociationToAddList",
	IDAMFTNLAssociationToRemoveList:               "AMF-TNLAssociationToRemoveList",
	IDAMFTNLAssociationToUpdateList:               "AMF-TNLAssociationToUpdateList",
	IDAMFTrafficLoadReductionIndication:           "AMFTrafficLoadReductionIndication",
	IDAMFUENGAPID:                                 "AMF-UE-NGAP-ID",
	IDAssistanceDataForPaging:                     "AssistanceDataForPaging",
	IDBroadcastCancelledAreaList:                  "BroadcastCancelledAreaList",
	IDBroadcastCompletedAreaList:                  "BroadcastCompletedAreaList",
	IDCancelAllWarningMessages:                    "CancelAllWarningMessages",
	IDCause:                                       "Cause",
	IDCellIDListForRestart:                        "CellIDListForRestart",
	IDConcurrentWarningMessageInd:                 "ConcurrentWarningMessageInd",
	IDCoreNetworkAssistanceInformationForInactive: "CoreNetworkAssistanceInformationForInactive",
	IDCriticalityDiagnostics:                      "CriticalityDiagnostics",
	IDDataCodingScheme:                            "DataCodingScheme",
	IDDefaultPagingDRX:                            "DefaultPagingDRX",
	IDDirectForwardingPathAvailability:            "DirectForwardingPathAvailability",
	IDEmergencyAreaIDListForRestart:               "EmergencyAreaIDListForRestart",
	IDEmergencyFallbackIndicator:                  "EmergencyFallbackIndicator",
	IDEUTRACGI:                                    "EUTRA-CGI",
	IDFiveGSTMSI:                                  "FiveG-S-TMSI",
	IDGlobalRANNodeID:                             "GlobalRANNodeID",
	IDGUAMI:                                       "GUAMI",
	IDHandoverType:                                "HandoverType",
	IDIMSVoiceSupportIndicator:                    "IMSVoiceSupportIndicator",
	IDIndexToRFSP:                                 "IndexToRFSP",
	IDInfoOnRecommendedCellsAndRANNodesForPaging:  "InfoOnRecommendedCellsAndRANNodesForPaging",
	IDLocationReportingRequestType:                "LocationReportingRequestType",
	IDMaskedIMEISV:                                "MaskedIMEISV",
	IDMessageIdentifier:                           "MessageIdentifier",
	IDMobilityRestrictionList:                     "MobilityRestrictionList",
	IDNASC:                                        "NASC",
	IDNASPDU:                                      "NAS-PDU",
	IDNASSecurityParametersFromNGRAN:              "NASSecurityParametersFromNGRAN",
	IDNewAMFUENGAPID:                              "NewAMF-UE-NGAP-ID",
	IDNewSecurityContextInd:                       "NewSecurityContextInd",
	IDNGAPMessage:                                 "NGAP-Message",
	IDNGRANCGI:                                    "NGRAN-CGI",
	IDNGRANTraceID:                                "NGRANTraceID",
	IDNRCGI:                                       "NR-CGI",
	IDNRPPaPDU:                                    "NRPPa-PDU",
	IDNumberOfBroadcastsRequested:                 "NumberOfBroadcastsRequested",
	IDOldAMF:                                      "OldAMF",
	IDOverloadStartNSSAIList:                      "OverloadStartNSSAIList",
	IDPagingDRX:                                   "PagingDRX",
	IDPagingOrigin:                                "PagingOrigin",
	IDPagingPriority:                              "PagingPriority",
	IDPDUSessionResourceAdmittedList:              "PDUSessionResourceAdmittedList",
	IDPDUSessionResourceFailedToModifyListModRes:  "PDUSessionResourceFailedToModifyListModRes",
	IDPDUSessionResourceFailedToSetupListCxtRes:   "PDUSessionResourceFailedToSetupListCxtRes",
	IDPDUSessionResourceFailedToSetupListHOAck:    "PDUSessionResourceFailedToSetupListHOAck",
	IDPDUSessionResourceFailedToSetupListPSReq:    "PDUSessionResourceFailedToSetupListPSReq",
	IDPDUSessionResourceFailedToSetupListSURes:    "PDUSessionResourceFailedToSetupListSURes",
	IDPDUSessionResourceHandoverList:              "PDUSessionResourceHandoverList",
	IDPDUSessionResourceListCxtRelCpl:             "PDUSessionResourceListCxtRelCpl",
	IDPDUSessionResourceListHORqd:                 "PDUSessionResourceListHORqd",
	IDPDUSessionResourceModifyListModCfm:          "PDUSessionResourceModifyListModCfm",
	IDPDUSessionResourceModifyListModInd:          "PDUSessionResourceModifyListModInd",
	IDPDUSessionResourceModifyListModReq:          "PDUSessionResourceModifyListModReq",
	IDPDUSessionResourceModifyListModRes:          "PDUSessionResourceModifyListModRes",
	IDPDUSessionResourceNotifyList:                "PDUSessionResourceNotifyList",
	IDPDUSessionResourceReleasedListNot:           "PDUSessionResourceReleasedListNot",
	IDPDUSessionResourceReleasedListPSAck:         "PDUSessionResourceReleasedListPSAck",
	IDPDUSessionResourceReleasedListPSFail:        "PDUSessionResourceReleasedListPSFail",
	IDPDUSessionResourceReleasedListRelRes:        "PDUSessionResourceReleasedListRelRes",
	IDPDUSessionResourceSetupListCxtReq:           "PDUSessionResourceSetupListCxtReq",
	IDPDUSessionResourceSetupListCxtRes:           "PDUSessionResourceSetupListCxtRes",
	IDPDUSessionResourceSetupListHOReq:            "PDUSessionResourceSetupListHOReq",
	IDPDUSessionResourceSetupListSUReq:            "PDUSessionResourceSetupListSUReq",
	IDPDUSessionResourceSetupListSURes:            "PDUSessionResourceSetupListSURes",
	IDPDUSessionResourceToBeSwitchedDLList:        "PDUSessionResourceToBeSwitchedDLList",
	IDPDUSessionResourceSwitchedList:              "PDUSessionResourceSwitchedList",
	IDPDUSessionResourceToReleaseListHOCmd:        "PDUSessionResourceToReleaseListHOCmd",
	IDPDUSessionResourceToReleaseListRelCmd:       "PDUSessionResourceToReleaseListRelCmd",
	IDPLMNSupportList:                             "PLMNSupportList",
	IDPWSFailedCellIDList:                         "PWSFailedCellIDList",
	IDRANNodeName:                                 "RANNodeName",
	IDRANPagingPriority:                           "RANPagingPriority",
	IDRANStatusTransferTransparentContainer:       "RANStatusTransfer-TransparentContainer",
	IDRANUENGAPID:                                 "RAN-UE-NGAP-ID",
	IDRelativeAMFCapacity:                         "RelativeAMFCapacity",
	IDRepetitionPeriod:                            "RepetitionPeriod",
	IDResetType:                                   "ResetType",
	IDRoutingID:                                   "RoutingID",
	IDRRCEstablishmentCause:                       "RRCEstablishmentCause",
	IDRRCInactiveTransitionReportRequest:          "RRCInactiveTransitionReportRequest",
	IDRRCState:                                    "RRCState",
	IDSecurityContext:                             "SecurityContext",
	IDSecurityKey:                                 "SecurityKey",
	IDSerialNumber:                                "SerialNumber",
	IDServedGUAMIList:                             "ServedGUAMIList",
	IDSliceSupportList:                            "SliceSupportList",
	IDSONConfigurationTransferDL:                  "SONConfigurationTransferDL",
	IDSONConfigurationTransferUL:                  "SONConfigurationTransferUL",
	IDSourceAMFUENGAPID:                           "SourceAMF-UE-NGAP-ID",
	IDSourceToTargetTransparentContainer:          "SourceToTarget-TransparentContainer",
	IDSupportedTAList:                             "SupportedTAList",
	IDTAIListForPaging:                            "TAIListForPaging",
	IDTAIListForRestart:                           "TAIListForRestart",
	IDTargetID:                                    "TargetID",
	IDTargetToSourceTransparentContainer:          "TargetToSource-TransparentContainer",
	IDTimeToWait:                                  "TimeToWait",
	IDTraceActivation:                             "TraceActivation",
	IDTraceCollectionEntityIPAddress:              "TraceCollectionEntityIPAddress",
	IDUEAggregateMaximumBitRate:                   "UEAggregateMaximumBitRate",
	IDUEAssociatedLogicalNGConnectionList:         "UE-associatedLogicalNG-connectionList",
	IDUEContextRequest:                            "UEContextRequest",
	IDUENGAPIDs:                                   "UE-NGAP-IDs",
	IDUEPagingIdentity:                            "UEPagingIdentity",
	IDUEPresenceInAreaOfInterestList:              "UEPresenceInAreaOfInterestList",
	IDUERadioCapability:                           "UERadioCapability",
	IDUERadioCapabilityForPaging:                  "UERadioCapabilityForPaging",
	IDUESecurityCapabilities:                      "UESecurityCapabilities",
	IDUnavailableGUAMIList:                        "UnavailableGUAMIList",
	IDUserLocationInformation:                     "UserLocationInformation",
	IDWarningAreaList:                             "WarningAreaList",
	IDWarningMessageContents:                      "WarningMessageContents",
	IDWarningSecurityInfo:                         "WarningSecurityInfo",
	IDWarningType:                                 "WarningType",
	IDAdditionalULNGUUPTNLInformation:             "AdditionalUL-NGU-UP-TNLInformation",
	IDDataForwardingNotPossible:                   "DataForwardingNotPossible",
	IDDLNGUUPTNLInformation:                       "DL-NGU-UP-TNLInformation",
	IDNetworkInstance:                             "NetworkInstance",
	IDPDUSessionAggregateMaximumBitRate:           "PDUSessionAggregateMaximumBitRate",
	IDPDUSessionResourceFailedToModifyListModCfm:  "PDUSessionResourceFailedToModifyListModCfm",
	IDPDUSessionResourceFailedToSetupListCxtFail:  "PDUSessionResourceFailedToSetupListCxtFail",
	IDPDUSessionResourceListCxtRelReq:             "PDUSessionResourceListCxtRelReq",
	IDPDUSessionType:                              "PDUSessionType",
	IDQosFlowAddOrModifyRequestList:               "QosFlowAddOrModifyRequestList",
	IDQosFlowSetupRequestList:                     "QosFlowSetupRequestList",
	IDQosFlowToReleaseList:                        "QosFlowToReleaseList",
	IDSecurityIndication:                          "SecurityIndication",
	IDULNGUUPTNLInformation:                       "UL-NGU-UP-TNLInformation",
	IDULNGUUPTNLModifyList:                        "UL-NGU-UP-TNLModifyList",
	IDWarningAreaCoordinates:                      "WarningAreaCoordinates",
	IDPDUSessionResourceSecondaryRATUsageList:     "PDUSessionResourceSecondaryRATUsageList",
	IDHandoverFlag:                                "HandoverFlag",
	IDSecondaryRATUsageInformation:                "SecondaryRATUsageInformation",
	IDPDUSessionResourceReleaseResponseTransfer:   "PDUSessionResourceReleaseResponseTransfer",
	IDRedirectionVoiceFallback:                    "RedirectionVoiceFallback",
	IDUERetentionInformation:                      "UERetentionInformation",
	IDSNSSAI:                                      "S-NSSAI",
	IDPSCellInformation:                           "PSCellInformation",
	IDLastEUTRANPLMNIdentity:                      "LastEUTRAN-PLMNIdentity",
	IDMaximumIntegrityProtectedDataRateDL:         "MaximumIntegrityProtectedDataRate-DL",
	IDAdditionalDLForwardingUPTNLInformation:      "AdditionalDLForwardingUPTNLInformation",
	IDAdditionalDLUPTNLInformationForHOList:       "AdditionalDLUPTNLInformationForHOList",
	IDAdditionalNGUUPTNLInformation:               "AdditionalNGU-UP-TNLInformation",
	IDAdditionalDLQosFlowPerTNLInformation:        "AdditionalDLQosFlowPerTNLInformation",
	IDSecurityResult:                              "SecurityResult",
	IDENDCSONConfigurationTransferDL:              "ENDC-SONConfigurationTransferDL",
	IDENDCSONConfigurationTransferUL:              "ENDC-SONConfigurationTransferUL",
	IDNGRANTNLAssociationToRemoveList:             "NGRAN-TNLAssociationToRemoveList",
	IDTargettoSourceFailureTransparentContainer:   "TargettoSource-Failure-TransparentContainer",
	IDNotifySourceNGRANNode:                       "NotifySourceNGRANNode",
}

// ProtocolIEIDName returns the TS 38.413 name of id, and whether it is known.
func ProtocolIEIDName(id ProtocolIEID) (string, bool) {
	name, ok := protocolIENames[id]

	return name, ok
}

func (id ProtocolIEID) String() string {
	if name, ok := ProtocolIEIDName(id); ok {
		return fmt.Sprintf("%s (%d)", name, uint16(id))
	}

	return fmt.Sprintf("ProtocolIEID(%d)", uint16(id))
}
