// Code generated by pergen. DO NOT EDIT.

//go:build !ignore

package ngap

import "github.com/ellanetworks/core/per"

func (broadcastPLMNItem *BroadcastPLMNItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := broadcastPLMNItem.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := broadcastPLMNItem.TAISliceSupportList.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (broadcastPLMNItem *BroadcastPLMNItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&broadcastPLMNItem.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&broadcastPLMNItem.TAISliceSupportList).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (criticalityDiagnosticsIEItem *CriticalityDiagnosticsIEItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := per.EncodeEnumerated(w, enc, 3, false, int64(criticalityDiagnosticsIEItem.IECriticality)); err != nil {
		return err
	}
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 65535, HasUB: true}, int64(criticalityDiagnosticsIEItem.IEID)); err != nil {
		return err
	}
	if err := per.EncodeEnumerated(w, enc, 2, true, int64(criticalityDiagnosticsIEItem.TypeOfError)); err != nil {
		return err
	}
	return nil
}

func (criticalityDiagnosticsIEItem *CriticalityDiagnosticsIEItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	e0, err := per.DecodeEnumerated(r, enc, 3, false)
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.IECriticality = Criticality(e0)
	n1, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 65535, HasUB: true})
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.IEID = ProtocolIEID(n1)
	e2, err := per.DecodeEnumerated(r, enc, 2, true)
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.TypeOfError = TypeOfError(e2)
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (fiveGSTMSI *FiveGSTMSI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := fiveGSTMSI.AMFSetID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := fiveGSTMSI.AMFPointer.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := fiveGSTMSI.FiveGTMSI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (fiveGSTMSI *FiveGSTMSI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&fiveGSTMSI.AMFSetID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&fiveGSTMSI.AMFPointer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&fiveGSTMSI.FiveGTMSI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (gUAMI *GUAMI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := gUAMI.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gUAMI.AMFRegionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gUAMI.AMFSetID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gUAMI.AMFPointer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (gUAMI *GUAMI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f4, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&gUAMI.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gUAMI.AMFRegionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gUAMI.AMFSetID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gUAMI.AMFPointer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f4 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (nGRANTNLAssociationToRemoveItem *NGRANTNLAssociationToRemoveItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddressAMF != nil)
	w.WriteBit(false)
	if err := nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddressAMF != nil {
		if err := (*nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddressAMF).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (nGRANTNLAssociationToRemoveItem *NGRANTNLAssociationToRemoveItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_TNLAssociationTransportLayerAddressAMF, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_TNLAssociationTransportLayerAddressAMF {
		var v CPTransportLayerInformation
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddressAMF = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pLMNSupportItem *PLMNSupportItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pLMNSupportItem.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pLMNSupportItem.SliceSupportList.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pLMNSupportItem *PLMNSupportItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pLMNSupportItem.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pLMNSupportItem.SliceSupportList).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (sNSSAI *SNSSAI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(sNSSAI.SD != nil)
	w.WriteBit(false)
	if err := sNSSAI.SST.MarshalPER(w, enc); err != nil {
		return err
	}
	if sNSSAI.SD != nil {
		if err := (*sNSSAI.SD).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (sNSSAI *SNSSAI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_SD, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&sNSSAI.SST).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_SD {
		var v SD
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		sNSSAI.SD = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (servedGUAMIItem *ServedGUAMIItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(servedGUAMIItem.BackupAMFName != nil)
	w.WriteBit(false)
	if err := servedGUAMIItem.GUAMI.MarshalPER(w, enc); err != nil {
		return err
	}
	if servedGUAMIItem.BackupAMFName != nil {
		if err := (*servedGUAMIItem.BackupAMFName).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (servedGUAMIItem *ServedGUAMIItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_BackupAMFName, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&servedGUAMIItem.GUAMI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_BackupAMFName {
		var v Name
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		servedGUAMIItem.BackupAMFName = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (sliceSupportItem *SliceSupportItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := sliceSupportItem.SNSSAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (sliceSupportItem *SliceSupportItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&sliceSupportItem.SNSSAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (supportedTAItem *SupportedTAItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := supportedTAItem.TAC.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := supportedTAItem.BroadcastPLMNList.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (supportedTAItem *SupportedTAItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&supportedTAItem.TAC).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&supportedTAItem.BroadcastPLMNList).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (uEAssociatedLogicalNGConnectionItem *UEAssociatedLogicalNGConnectionItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(uEAssociatedLogicalNGConnectionItem.AMFUENGAPID != nil)
	w.WriteBit(uEAssociatedLogicalNGConnectionItem.RANUENGAPID != nil)
	w.WriteBit(false)
	if uEAssociatedLogicalNGConnectionItem.AMFUENGAPID != nil {
		if err := (*uEAssociatedLogicalNGConnectionItem.AMFUENGAPID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if uEAssociatedLogicalNGConnectionItem.RANUENGAPID != nil {
		if err := (*uEAssociatedLogicalNGConnectionItem.RANUENGAPID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (uEAssociatedLogicalNGConnectionItem *UEAssociatedLogicalNGConnectionItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_AMFUENGAPID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_RANUENGAPID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if p_AMFUENGAPID {
		var v AMFUENGAPID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		uEAssociatedLogicalNGConnectionItem.AMFUENGAPID = &v
	}
	if p_RANUENGAPID {
		var v RANUENGAPID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		uEAssociatedLogicalNGConnectionItem.RANUENGAPID = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}
