// Code generated by pergen. DO NOT EDIT.

//go:build !ignore

package ngap

import "github.com/ellanetworks/core/per"

func (allowedNSSAIItem *AllowedNSSAIItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := allowedNSSAIItem.SNSSAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (allowedNSSAIItem *AllowedNSSAIItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&allowedNSSAIItem.SNSSAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (broadcastPLMNItem *BroadcastPLMNItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := broadcastPLMNItem.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := broadcastPLMNItem.TAISliceSupportList.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (broadcastPLMNItem *BroadcastPLMNItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&broadcastPLMNItem.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&broadcastPLMNItem.TAISliceSupportList).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (criticalityDiagnosticsIEItem *CriticalityDiagnosticsIEItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := per.EncodeEnumerated(w, enc, 3, false, int64(criticalityDiagnosticsIEItem.IECriticality)); err != nil {
		return err
	}
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 65535, HasUB: true}, int64(criticalityDiagnosticsIEItem.IEID)); err != nil {
		return err
	}
	if err := encodeRootEnumerated(w, enc, 2, int64(criticalityDiagnosticsIEItem.TypeOfError), "TypeOfError"); err != nil {
		return err
	}
	return nil
}

func (criticalityDiagnosticsIEItem *CriticalityDiagnosticsIEItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	e0, err := per.DecodeEnumerated(r, enc, 3, false)
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.IECriticality = Criticality(e0)
	n1, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 65535, HasUB: true})
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.IEID = ProtocolIEID(n1)
	e2, err := decodeRootEnumerated(r, enc, 2, "TypeOfError")
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.TypeOfError = TypeOfError(e2)
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (fiveGSTMSI *FiveGSTMSI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := fiveGSTMSI.AMFSetID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := fiveGSTMSI.AMFPointer.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := fiveGSTMSI.FiveGTMSI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (fiveGSTMSI *FiveGSTMSI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&fiveGSTMSI.AMFSetID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&fiveGSTMSI.AMFPointer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&fiveGSTMSI.FiveGTMSI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (gUAMI *GUAMI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := gUAMI.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gUAMI.AMFRegionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gUAMI.AMFSetID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gUAMI.AMFPointer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (gUAMI *GUAMI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f4, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&gUAMI.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gUAMI.AMFRegionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gUAMI.AMFSetID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gUAMI.AMFPointer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f4 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (nGRANTNLAssociationToRemoveItem *NGRANTNLAssociationToRemoveItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddressAMF != nil)
	w.WriteBit(false)
	if err := nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddressAMF != nil {
		if err := (*nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddressAMF).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (nGRANTNLAssociationToRemoveItem *NGRANTNLAssociationToRemoveItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	p_TNLAssociationTransportLayerAddressAMF, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_TNLAssociationTransportLayerAddressAMF {
		var v CPTransportLayerInformation
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		nGRANTNLAssociationToRemoveItem.TNLAssociationTransportLayerAddressAMF = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	return nil
}

func (pDUSessionResourceFailedToModifyItemModCfm *PDUSessionResourceFailedToModifyItemModCfm) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceFailedToModifyItemModCfm.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceFailedToModifyItemModCfm.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceFailedToModifyItemModCfm *PDUSessionResourceFailedToModifyItemModCfm) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToModifyItemModCfm.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToModifyItemModCfm.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceFailedToModifyItemModRes *PDUSessionResourceFailedToModifyItemModRes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceFailedToModifyItemModRes.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceFailedToModifyItemModRes.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceFailedToModifyItemModRes *PDUSessionResourceFailedToModifyItemModRes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToModifyItemModRes.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToModifyItemModRes.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceFailedToSetupItemCxtFail *PDUSessionResourceFailedToSetupItemCxtFail) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceFailedToSetupItemCxtFail.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceFailedToSetupItemCxtFail.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceFailedToSetupItemCxtFail *PDUSessionResourceFailedToSetupItemCxtFail) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToSetupItemCxtFail.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToSetupItemCxtFail.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceFailedToSetupItemCxtRes *PDUSessionResourceFailedToSetupItemCxtRes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceFailedToSetupItemCxtRes.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceFailedToSetupItemCxtRes.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceFailedToSetupItemCxtRes *PDUSessionResourceFailedToSetupItemCxtRes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToSetupItemCxtRes.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToSetupItemCxtRes.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceFailedToSetupItemSURes *PDUSessionResourceFailedToSetupItemSURes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceFailedToSetupItemSURes.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceFailedToSetupItemSURes.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceFailedToSetupItemSURes *PDUSessionResourceFailedToSetupItemSURes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToSetupItemSURes.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceFailedToSetupItemSURes.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceItemCxtRelCpl *PDUSessionResourceItemCxtRelCpl) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceItemCxtRelCpl.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceItemCxtRelCpl *PDUSessionResourceItemCxtRelCpl) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceItemCxtRelCpl.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceItemCxtRelReq *PDUSessionResourceItemCxtRelReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceItemCxtRelReq.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceItemCxtRelReq *PDUSessionResourceItemCxtRelReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceItemCxtRelReq.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceModifyIndicationUnsuccessfulTransfer *PDUSessionResourceModifyIndicationUnsuccessfulTransfer) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceModifyIndicationUnsuccessfulTransfer.Cause.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceModifyIndicationUnsuccessfulTransfer *PDUSessionResourceModifyIndicationUnsuccessfulTransfer) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceModifyIndicationUnsuccessfulTransfer.Cause).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceModifyItemModCfm *PDUSessionResourceModifyItemModCfm) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceModifyItemModCfm.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceModifyItemModCfm.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceModifyItemModCfm *PDUSessionResourceModifyItemModCfm) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceModifyItemModCfm.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceModifyItemModCfm.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceModifyItemModInd *PDUSessionResourceModifyItemModInd) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceModifyItemModInd.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceModifyItemModInd.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceModifyItemModInd *PDUSessionResourceModifyItemModInd) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceModifyItemModInd.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceModifyItemModInd.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceModifyItemModReq *PDUSessionResourceModifyItemModReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(pDUSessionResourceModifyItemModReq.NASPDU != nil)
	w.WriteBit(false)
	if err := pDUSessionResourceModifyItemModReq.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if pDUSessionResourceModifyItemModReq.NASPDU != nil {
		if err := (*pDUSessionResourceModifyItemModReq.NASPDU).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if err := pDUSessionResourceModifyItemModReq.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceModifyItemModReq *PDUSessionResourceModifyItemModReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_NASPDU, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceModifyItemModReq.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_NASPDU {
		var v NASPDU
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		pDUSessionResourceModifyItemModReq.NASPDU = &v
	}
	if err := (&pDUSessionResourceModifyItemModReq.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceModifyItemModRes *PDUSessionResourceModifyItemModRes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceModifyItemModRes.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceModifyItemModRes.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceModifyItemModRes *PDUSessionResourceModifyItemModRes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceModifyItemModRes.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceModifyItemModRes.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceNotifyItem *PDUSessionResourceNotifyItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceNotifyItem.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceNotifyItem.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceNotifyItem *PDUSessionResourceNotifyItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceNotifyItem.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceNotifyItem.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceReleasedItemNot *PDUSessionResourceReleasedItemNot) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceReleasedItemNot.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceReleasedItemNot.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceReleasedItemNot *PDUSessionResourceReleasedItemNot) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceReleasedItemNot.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceReleasedItemNot.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceReleasedItemRelRes *PDUSessionResourceReleasedItemRelRes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceReleasedItemRelRes.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceReleasedItemRelRes.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceReleasedItemRelRes *PDUSessionResourceReleasedItemRelRes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceReleasedItemRelRes.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceReleasedItemRelRes.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceSetupItemCxtReq *PDUSessionResourceSetupItemCxtReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(pDUSessionResourceSetupItemCxtReq.NASPDU != nil)
	w.WriteBit(false)
	if err := pDUSessionResourceSetupItemCxtReq.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if pDUSessionResourceSetupItemCxtReq.NASPDU != nil {
		if err := (*pDUSessionResourceSetupItemCxtReq.NASPDU).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if err := pDUSessionResourceSetupItemCxtReq.SNSSAI.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceSetupItemCxtReq.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceSetupItemCxtReq *PDUSessionResourceSetupItemCxtReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_NASPDU, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f4, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceSetupItemCxtReq.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_NASPDU {
		var v NASPDU
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		pDUSessionResourceSetupItemCxtReq.NASPDU = &v
	}
	if err := (&pDUSessionResourceSetupItemCxtReq.SNSSAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceSetupItemCxtReq.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f4 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceSetupItemCxtRes *PDUSessionResourceSetupItemCxtRes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceSetupItemCxtRes.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceSetupItemCxtRes.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceSetupItemCxtRes *PDUSessionResourceSetupItemCxtRes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceSetupItemCxtRes.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceSetupItemCxtRes.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceSetupItemSUReq *PDUSessionResourceSetupItemSUReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(pDUSessionResourceSetupItemSUReq.NASPDU != nil)
	w.WriteBit(false)
	if err := pDUSessionResourceSetupItemSUReq.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if pDUSessionResourceSetupItemSUReq.NASPDU != nil {
		if err := (*pDUSessionResourceSetupItemSUReq.NASPDU).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if err := pDUSessionResourceSetupItemSUReq.SNSSAI.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceSetupItemSUReq.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceSetupItemSUReq *PDUSessionResourceSetupItemSUReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_NASPDU, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f4, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceSetupItemSUReq.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_NASPDU {
		var v NASPDU
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		pDUSessionResourceSetupItemSUReq.NASPDU = &v
	}
	if err := (&pDUSessionResourceSetupItemSUReq.SNSSAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceSetupItemSUReq.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f4 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceSetupItemSURes *PDUSessionResourceSetupItemSURes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceSetupItemSURes.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceSetupItemSURes.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceSetupItemSURes *PDUSessionResourceSetupItemSURes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceSetupItemSURes.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceSetupItemSURes.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pDUSessionResourceToReleaseItemRelCmd *PDUSessionResourceToReleaseItemRelCmd) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pDUSessionResourceToReleaseItemRelCmd.PDUSessionID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pDUSessionResourceToReleaseItemRelCmd.Transfer.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pDUSessionResourceToReleaseItemRelCmd *PDUSessionResourceToReleaseItemRelCmd) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pDUSessionResourceToReleaseItemRelCmd.PDUSessionID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pDUSessionResourceToReleaseItemRelCmd.Transfer).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (pLMNSupportItem *PLMNSupportItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := pLMNSupportItem.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := pLMNSupportItem.SliceSupportList.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (pLMNSupportItem *PLMNSupportItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&pLMNSupportItem.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&pLMNSupportItem.SliceSupportList).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (sNSSAI *SNSSAI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(sNSSAI.SD != nil)
	w.WriteBit(false)
	if err := sNSSAI.SST.MarshalPER(w, enc); err != nil {
		return err
	}
	if sNSSAI.SD != nil {
		if err := (*sNSSAI.SD).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (sNSSAI *SNSSAI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_SD, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&sNSSAI.SST).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_SD {
		var v SD
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		sNSSAI.SD = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (servedGUAMIItem *ServedGUAMIItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(servedGUAMIItem.BackupAMFName != nil)
	w.WriteBit(false)
	if err := servedGUAMIItem.GUAMI.MarshalPER(w, enc); err != nil {
		return err
	}
	if servedGUAMIItem.BackupAMFName != nil {
		if err := (*servedGUAMIItem.BackupAMFName).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (servedGUAMIItem *ServedGUAMIItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_BackupAMFName, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&servedGUAMIItem.GUAMI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_BackupAMFName {
		var v Name
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		servedGUAMIItem.BackupAMFName = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (sliceSupportItem *SliceSupportItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := sliceSupportItem.SNSSAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (sliceSupportItem *SliceSupportItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&sliceSupportItem.SNSSAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (supportedTAItem *SupportedTAItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := supportedTAItem.TAC.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := supportedTAItem.BroadcastPLMNList.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (supportedTAItem *SupportedTAItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&supportedTAItem.TAC).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&supportedTAItem.BroadcastPLMNList).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (tAI *TAI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := tAI.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := tAI.TAC.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (tAI *TAI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&tAI.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&tAI.TAC).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (targetRANNodeIDSON *TargetRANNodeIDSON) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := targetRANNodeIDSON.GlobalRANNodeID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := targetRANNodeIDSON.SelectedTAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (targetRANNodeIDSON *TargetRANNodeIDSON) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&targetRANNodeIDSON.GlobalRANNodeID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&targetRANNodeIDSON.SelectedTAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (uEAggregateMaximumBitRate *UEAggregateMaximumBitRate) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := uEAggregateMaximumBitRate.DL.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := uEAggregateMaximumBitRate.UL.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (uEAggregateMaximumBitRate *UEAggregateMaximumBitRate) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&uEAggregateMaximumBitRate.DL).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&uEAggregateMaximumBitRate.UL).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (uEAssociatedLogicalNGConnectionItem *UEAssociatedLogicalNGConnectionItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(uEAssociatedLogicalNGConnectionItem.AMFUENGAPID != nil)
	w.WriteBit(uEAssociatedLogicalNGConnectionItem.RANUENGAPID != nil)
	w.WriteBit(false)
	if uEAssociatedLogicalNGConnectionItem.AMFUENGAPID != nil {
		if err := (*uEAssociatedLogicalNGConnectionItem.AMFUENGAPID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if uEAssociatedLogicalNGConnectionItem.RANUENGAPID != nil {
		if err := (*uEAssociatedLogicalNGConnectionItem.RANUENGAPID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (uEAssociatedLogicalNGConnectionItem *UEAssociatedLogicalNGConnectionItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_AMFUENGAPID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_RANUENGAPID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if p_AMFUENGAPID {
		var v AMFUENGAPID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		uEAssociatedLogicalNGConnectionItem.AMFUENGAPID = &v
	}
	if p_RANUENGAPID {
		var v RANUENGAPID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		uEAssociatedLogicalNGConnectionItem.RANUENGAPID = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (uERadioCapabilityForPaging *UERadioCapabilityForPaging) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(uERadioCapabilityForPaging.NR != nil)
	w.WriteBit(uERadioCapabilityForPaging.EUTRA != nil)
	w.WriteBit(false)
	if uERadioCapabilityForPaging.NR != nil {
		if err := (*uERadioCapabilityForPaging.NR).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if uERadioCapabilityForPaging.EUTRA != nil {
		if err := (*uERadioCapabilityForPaging.EUTRA).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (uERadioCapabilityForPaging *UERadioCapabilityForPaging) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_NR, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_EUTRA, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if p_NR {
		var v UERadioCapabilityForPagingOfNR
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		uERadioCapabilityForPaging.NR = &v
	}
	if p_EUTRA {
		var v UERadioCapabilityForPagingOfEUTRA
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		uERadioCapabilityForPaging.EUTRA = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (unavailableGUAMIItem *UnavailableGUAMIItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(unavailableGUAMIItem.TimerApproachForGUAMIRemoval != nil)
	w.WriteBit(unavailableGUAMIItem.BackupAMFName != nil)
	w.WriteBit(false)
	if err := unavailableGUAMIItem.GUAMI.MarshalPER(w, enc); err != nil {
		return err
	}
	if unavailableGUAMIItem.TimerApproachForGUAMIRemoval != nil {
		if err := (*unavailableGUAMIItem.TimerApproachForGUAMIRemoval).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if unavailableGUAMIItem.BackupAMFName != nil {
		if err := (*unavailableGUAMIItem.BackupAMFName).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (unavailableGUAMIItem *UnavailableGUAMIItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_TimerApproachForGUAMIRemoval, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_BackupAMFName, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&unavailableGUAMIItem.GUAMI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_TimerApproachForGUAMIRemoval {
		var v TimerApproachForGUAMIRemoval
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		unavailableGUAMIItem.TimerApproachForGUAMIRemoval = &v
	}
	if p_BackupAMFName {
		var v Name
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		unavailableGUAMIItem.BackupAMFName = &v
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (taiListForPagingItem *taiListForPagingItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := taiListForPagingItem.TAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (taiListForPagingItem *taiListForPagingItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&taiListForPagingItem.TAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}
