{
 "title": "Ella Core Network Health",
 "description": "Monitor your Ella Core deployment.",
 "tags": [
  "5g",
  "network",
  "health"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_MIMIR", "label": "Mimir", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Radios",
   "type": "stat",
   "description": "Live number of connected radios in Ella Core.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_connected_radios{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registration Success Rate",
   "type": "stat",
   "description": "Percentage of successful registration attempts by UE's in Ella Core over the last 5 minutes. ",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  100 * (\n    sum(rate(app_registration_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"accept\"}[$__rate_interval]))\n    /\n    sum(rate(app_registration_attempts_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n  )\n  and\n  sum(rate(app_registration_attempts_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) > 0\n)\nor vector(100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Session Establishment Success Rate",
   "type": "stat",
   "description": "Percentage of UE PDU Session Establishment Requests accepted by Ella Core over the last 5 minutes. ",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  100 * (\n    sum(rate(app_session_establishment_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"accept\"}[$__rate_interval]))\n    /\n    sum(rate(app_session_establishment_attempts_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n  )\n  and\n  sum(rate(app_session_establishment_attempts_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) > 0\n)\nor vector(100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active PDU Sessions",
   "type": "stat",
   "description": "Live number of active PDU sessions. ",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_sessions{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Throughput",
   "type": "stat",
   "description": "Total live throughput (uplink + downlink)",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_upf_bytes_total{job=~\"$job\",instance=~\"$instance\",direction=~\"uplink|downlink\"}[$__rate_interval])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "stat",
   "description": "Percentage of API requests returning 5xx status codes over the last 5 minutes.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(app_api_requests_total{job=~\"$job\",instance=~\"$instance\",status=~\"5..\"}[$__rate_interval])) or vector(0)) / \n(sum(rate(app_api_requests_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) > 0 or vector(1)) * 100",
     "legendFormat": " "
    }
   ]
  },
  { "title": "System Health and Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "description": "Amount of time since Ella Core started",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "description": "Percentage of Ella Core's available CPU used by the user space program. Does not include XDP packet processing.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) / go_sched_gomaxprocs_threads{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Total physical RAM used by the process",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Total size of the SQLite database.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_database_storage_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP Address Pool Utilization",
   "type": "stat",
   "description": "Cumulative IP pool utilization for all data networks configured in Ella Core.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * app_ip_addresses_allocated{job=~\"$job\",instance=~\"$instance\"} / app_ip_addresses{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Signaling Message Rate",
   "type": "timeseries",
   "description": "Received signaling messages per type.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(app_signaling_messages_total{job=~\"$job\",instance=~\"$instance\",}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Registered Subscribers",
   "type": "timeseries",
   "description": "Number of UEs in registered state.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "app_registered_subscribers{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Registered UEs"
    }
   ]
  },
  {
   "title": "Registration Attempts",
   "type": "timeseries",
   "description": "Rate of accepted vs rejected UE registration attempts per type.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(app_registration_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"accept\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}} (accept)"
    },
    {
     "expr": "sum(rate(app_registration_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"reject\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}} (reject)"
    }
   ]
  },
  {
   "title": "Active PDU Sessions",
   "type": "timeseries",
   "description": "Number of active PDU sessions in Ella Core.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(app_sessions{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Active PDU Sessions"
    }
   ]
  },
  {
   "title": "PDU Session Establishment Attempts",
   "type": "timeseries",
   "description": "Rate of accepted vs rejected PDU Session Establishment requests.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(app_session_establishment_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"accept\"}[$__rate_interval])",
     "legendFormat": "accept"
    },
    {
     "expr": "rate(app_session_establishment_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"reject\"}[$__rate_interval])",
     "legendFormat": "reject"
    }
   ]
  },
  { "title": "User Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Data Plane throughput",
   "type": "timeseries",
   "description": "Bitrate for uplink and downlink GTP traffic",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(app_upf_bytes_total{job=~\"$job\",instance=~\"$instance\",direction=\"uplink\"}[$__rate_interval]) * 8",
     "legendFormat": "Uplink"
    },
    {
     "expr": "rate(app_upf_bytes_total{job=~\"$job\",instance=~\"$instance\",direction=\"downlink\"}[$__rate_interval]) * 8",
     "legendFormat": "Downlink"
    }
   ]
  },
  {
   "title": "Data Plane Actions - N3",
   "type": "timeseries",
   "description": "Data plane action rate for packets arriving on the N3 interface (from the radio network).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(app_upf_datapath_forward_total{job=~\"$job\",instance=~\"$instance\",direction=\"uplink\",action=\"pass\"}[$__rate_interval])",
     "legendFormat": "PASS - Forwarded to network stack"
    },
    {
     "expr": "rate(app_upf_datapath_forward_total{job=~\"$job\",instance=~\"$instance\",direction=\"uplink\",action=\"tx\"}[$__rate_interval])",
     "legendFormat": "TX - Transmitted back out"
    },
    {
     "expr": "rate(app_upf_datapath_forward_total{job=~\"$job\",instance=~\"$instance\",direction=\"uplink\",action=\"redirect\"}[$__rate_interval])",
     "legendFormat": "REDIRECT - Redirected to another interface"
    },
    {
     "expr": "sum(rate(app_upf_datapath_drop_total{job=~\"$job\",instance=~\"$instance\",direction=\"uplink\"}[$__rate_interval]))",
     "legendFormat": "DROP - all reasons"
    },
    {
     "expr": "sum(rate(app_upf_datapath_drop_total{job=~\"$job\",instance=~\"$instance\",direction=\"uplink\",reason=~\"internal_.*\"}[$__rate_interval]))",
     "legendFormat": "DROP - datapath failures"
    }
   ]
  },
  {
   "title": "Data Plane Actions - N6",
   "type": "timeseries",
   "description": "Data plane action rate for packets arriving on the N6 interface (from the data network).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(app_upf_datapath_forward_total{job=~\"$job\",instance=~\"$instance\",direction=\"downlink\",action=\"pass\"}[$__rate_interval])",
     "legendFormat": "PASS - Forwarded to network stack"
    },
    {
     "expr": "rate(app_upf_datapath_forward_total{job=~\"$job\",instance=~\"$instance\",direction=\"downlink\",action=\"tx\"}[$__rate_interval])",
     "legendFormat": "TX - Transmitted back out"
    },
    {
     "expr": "rate(app_upf_datapath_forward_total{job=~\"$job\",instance=~\"$instance\",direction=\"downlink\",action=\"redirect\"}[$__rate_interval])",
     "legendFormat": "REDIRECT - Redirected to another interface"
    },
    {
     "expr": "sum(rate(app_upf_datapath_drop_total{job=~\"$job\",instance=~\"$instance\",direction=\"downlink\"}[$__rate_interval]))",
     "legendFormat": "DROP - all reasons"
    },
    {
     "expr": "sum(rate(app_upf_datapath_drop_total{job=~\"$job\",instance=~\"$instance\",direction=\"downlink\",reason=~\"internal_.*\"}[$__rate_interval]))",
     "legendFormat": "DROP - datapath failures"
    }
   ]
  },
  {
   "title": "API and Authentication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Request Rate",
     "type": "stat",
     "description": "Amount of API requests per second.",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(app_api_requests_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Request Rate by Endpoint",
     "type": "timeseries",
     "description": "Rate of API request per endpoint color coded by status code.",
     "gridPos": { "h": 9, "w": 13, "x": 3, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(app_api_requests_total{job=~\"$job\",instance=~\"$instance\",endpoint!~\"/api/v1/(pprof|metrics)\"}[$__rate_interval])",
       "legendFormat": "{{method}} {{endpoint}} ({{status}})"
      }
     ]
    },
    {
     "title": "API Latency Percentiles",
     "type": "timeseries",
     "description": "API latency percentiles per bucket. For example, a datapoint for p99 at 24.2ms means that 99% of requests take less than 24.2ms.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(app_api_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\",endpoint!~\"/api/v1/(pprof|metrics)\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "p50 (median)"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(app_api_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\",endpoint!~\"/api/v1/(pprof|metrics)\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(app_api_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\",endpoint!~\"/api/v1/(pprof|metrics)\"}[$__rate_interval])) by (le)\n)",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "API Authentication Success Rate",
     "type": "stat",
     "description": "Percentage of successful API authentication over the last 5 minutes.",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 *\nsum(rate(app_api_authentication_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"success\"}[$__rate_interval]))\n/\nsum(rate(app_api_authentication_attempts_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\nand\nsum(rate(app_api_authentication_attempts_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) > 0\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Authentication Attempts",
     "type": "timeseries",
     "description": "Rate of successful vs failed API authentication attempts",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(app_api_authentication_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"success\"}[$__rate_interval]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(rate(app_api_authentication_attempts_total{job=~\"$job\",instance=~\"$instance\",result=\"failure\"}[$__rate_interval]))",
       "legendFormat": "Failure"
      }
     ]
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Heap",
     "type": "timeseries",
     "description": "Memory In-Use Bytes (Heap)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Heap"
      }
     ]
    },
    {
     "title": "CPU Utilization Over Time",
     "type": "timeseries",
     "description": "Percentage of Ella Core's available CPU used by the process.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",}[$__rate_interval]) / go_sched_gomaxprocs_threads{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "Number of goroutines",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB Size",
     "type": "timeseries",
     "description": "Total Database file size",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "app_database_storage_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "DB Query Rate",
     "type": "timeseries",
     "description": "Rate of database queries by table and operation type",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(app_database_queries_total{job=~\"$job\",instance=~\"$instance\",}[$__rate_interval])",
       "legendFormat": "{{operation}} {{table}} "
      }
     ]
    },
    {
     "title": "DB Latency Percentiles",
     "type": "timeseries",
     "description": "DB latency percentiles per bucket. For example, a datapoint for p99 at 3.987ms means that 99% of requests take less than 3.987ms.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(app_database_query_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50 (median)"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(app_database_query_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(app_database_query_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  }
 ]
}