apiVersion: v1
kind: Service
metadata:
  name: ella-core
spec:
  selector:
    app: ella-core
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 5002
    targetPort: 5002
  - name: ngapp
    protocol: SCTP
    port: 38412
    targetPort: 38412
