apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ella-core
spec:
  replicas: 1
  serviceName: ella-core
  selector:
    matchLabels:
      app: ella-core
  template:
    metadata:
      labels:
        app: ella-core
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {"name": "core-ran", "interface": "n3"}
          ]
    spec:
      containers:
      - name: core
        image: ghcr.io/ellanetworks/ella-core:v1.19.0
        command: ["core"]
        args: ["--config", "/config/config.yaml"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: data
          mountPath: /core/data
        ports:
        - containerPort: 5002
      volumes:
      - name: config-volume
        configMap:
          name: core-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
