apiVersion: v1
kind: Service
metadata:
  name: ella
  namespace: dev2
spec:
  selector:
    app: ella
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: ngapp
    protocol: SCTP
    port: 38412
    targetPort: 38412
