apiVersion: apps/v1
kind: Deployment
metadata:
  name: ella
  namespace: dev2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ella
  template:
    metadata:
      labels:
        app: ella
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {"name": "n3-net", "interface": "n3"},
            {"name": "n6-net", "interface": "n6"}
          ]
    spec:
      initContainers:
      - name: setup-route
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          ip route replace default via 192.168.250.1 metric 110
          ip route replace 192.168.251.0/24 via 192.168.252.1
          sysctl -w net.ipv4.ip_forward=1
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
      containers:
      - name: ella
        image: localhost:5000/ella:0.0.4
        imagePullPolicy: Always
        command: ["pebble"]
        args: ["run", "--hold", "--http", ":38813", "--verbose"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: sysfs-bpf
          mountPath: /sys/fs/bpf
        - name: data-volume
          mountPath: /ella/data
        ports:
        - containerPort: 5000
        - containerPort: 38412
      - name: network-tools
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do sleep 3600; done
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: config-volume
        configMap:
          name: ella-config
      - name: data-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: sysfs-bpf
        hostPath:
          path: /sys/fs/bpf
          type: Directory
