apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnbsim
  namespace: dev2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnbsim
  template:
    metadata:
      labels:
        app: gnbsim
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "gnb-net",
              "interface": "gnb"
            }
          ]
    spec:
      initContainers:
      - name: init-route
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Setting up custom route..."
          ip route replace 192.168.252.0/24 via 192.168.251.1
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
      containers:
      - name: gnbsim
        image: ghcr.io/canonical/sdcore-gnbsim:1.4.5
        volumeMounts:
        - name: config-volume
          mountPath: /etc/gnbsim
        securityContext:
          privileged: true
        ports:
        - containerPort: 38412
      - name: network-tools
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do sleep 3600; done
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: config-volume
        configMap:
          name: gnbsim-config
