apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ella
resources:
  - namespace.yaml
  - core-configmap.yaml
  - core-statefulset.yaml
  - core-service.yaml
  - core-ran-nad.yaml
