apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  namespace: dev2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "core-gw",
              "interface": "core"
            },
            {
              "name": "access-gw",
              "interface": "access"
            },
            {
              "name": "ran-gw",
              "interface": "ran"
            }
          ]
    spec:
      containers:
      - name: router
        image: ghcr.io/canonical/ubuntu-router:0.1
        command: ["/bin/bash", "-c"]
        args:
          - >
            sysctl -w net.ipv4.ip_forward=1;
            iptables-legacy -t nat -A POSTROUTING -o eth0 -j MASQUERADE;
            trap : TERM INT; sleep infinity & wait
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
      - name: network-tools
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do sleep 3600; done
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
