apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-config
data:
  gnb.yaml: |
    mcc: '001'
    mnc: '01'

    nci: '0x000000010'
    idLength: 32
    tac: 1

    linkIp: 127.0.0.1
    ngapIp: 192.168.253.6
    gtpIp:  192.168.252.6

    amfConfigs:
      - address: 192.168.253.3
        port: 38412

    slices:
      - sst: 0x1
        sd: 0x102030

    ignoreStreamIds: true
  ue.yaml: |
    supi: 'imsi-001010100000001'
    mcc: '001'
    mnc: '01'
    protectionScheme: 0
    homeNetworkPublicKey: '75d1dde9519b390b172104ae3397557a114acbd39d3c39b2bcc3ce282abc4c3e'
    homeNetworkPublicKeyId: 1
    routingIndicator: '0000'

    key: '5122250214c33e723a5dd523fc145fc0'
    op: '981d464c7c52eb6e5036234984ad0bcf'
    opType: 'OPC'
    amf: '8000'
    imei: '356938035643803'
    imeiSv: '4370816125816151'

    gnbSearchList:
      - 127.0.0.1

    uacAic:
      mps: false
      mcs: false

    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false

    sessions:
      - type: 'IPv4'
        apn: 'internet'
        slice:
          sst: 0x01
          sd: 0x102030

    configured-nssai:
      - sst: 0x01
        sd: 0x102030

    default-nssai:
      - sst: 1
        sd: 1

    integrity:
      IA1: true
      IA2: true
      IA3: true

    ciphering:
      EA1: true
      EA2: true
      EA3: true

    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'