server:
  http_listen_port: 3200

query_frontend:
  mcp_server:
    enabled: true

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

backend_scheduler:
  provider:
    compaction:
      compaction:
        block_retention: 720h

backend_worker:
  compaction:
    block_retention: 720h

metrics_generator:
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://ella-mimir:9009/api/v1/push
        send_exemplars: true

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

overrides:
  defaults:
    metrics_generator:
      processors:
        - span-metrics
        - service-graphs
