// Code generated by pergen. DO NOT EDIT.

//go:build !ignore

package s1ap

import "github.com/ellanetworks/core/per"

func (allocationAndRetentionPriority *AllocationAndRetentionPriority) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 15, HasUB: true}, int64(allocationAndRetentionPriority.PriorityLevel)); err != nil {
		return err
	}
	if err := per.EncodeEnumerated(w, enc, 2, false, int64(allocationAndRetentionPriority.PreemptionCapability)); err != nil {
		return err
	}
	if err := per.EncodeEnumerated(w, enc, 2, false, int64(allocationAndRetentionPriority.PreemptionVulnerability)); err != nil {
		return err
	}
	return nil
}

func (allocationAndRetentionPriority *AllocationAndRetentionPriority) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	n0, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 15, HasUB: true})
	if err != nil {
		return err
	}
	allocationAndRetentionPriority.PriorityLevel = uint8(n0)
	e1, err := per.DecodeEnumerated(r, enc, 2, false)
	if err != nil {
		return err
	}
	allocationAndRetentionPriority.PreemptionCapability = PreemptionCapability(e1)
	e2, err := per.DecodeEnumerated(r, enc, 2, false)
	if err != nil {
		return err
	}
	allocationAndRetentionPriority.PreemptionVulnerability = PreemptionVulnerability(e2)
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (criticalityDiagnosticsIEItem *CriticalityDiagnosticsIEItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := per.EncodeEnumerated(w, enc, 3, false, int64(criticalityDiagnosticsIEItem.IECriticality)); err != nil {
		return err
	}
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 65535, HasUB: true}, int64(criticalityDiagnosticsIEItem.IEID)); err != nil {
		return err
	}
	if err := encodeRootEnumerated(w, enc, 2, int64(criticalityDiagnosticsIEItem.TypeOfError), "TypeOfError"); err != nil {
		return err
	}
	return nil
}

func (criticalityDiagnosticsIEItem *CriticalityDiagnosticsIEItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	e0, err := per.DecodeEnumerated(r, enc, 3, false)
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.IECriticality = Criticality(e0)
	n1, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 65535, HasUB: true})
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.IEID = ProtocolIEID(n1)
	e2, err := decodeRootEnumerated(r, enc, 2, "TypeOfError")
	if err != nil {
		return err
	}
	criticalityDiagnosticsIEItem.TypeOfError = TypeOfError(e2)
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABAdmittedItem *ERABAdmittedItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(eRABAdmittedItem.DLTransportLayerAddr != nil)
	w.WriteBit(eRABAdmittedItem.DLGTPTEID != nil)
	w.WriteBit(eRABAdmittedItem.ULTransportLayerAddr != nil)
	w.WriteBit(eRABAdmittedItem.ULGTPTEID != nil)
	w.WriteBit(false)
	if err := eRABAdmittedItem.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABAdmittedItem.TransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABAdmittedItem.GTPTEID.MarshalPER(w, enc); err != nil {
		return err
	}
	if eRABAdmittedItem.DLTransportLayerAddr != nil {
		if err := eRABAdmittedItem.DLTransportLayerAddr.MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if eRABAdmittedItem.DLGTPTEID != nil {
		if err := (*eRABAdmittedItem.DLGTPTEID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if eRABAdmittedItem.ULTransportLayerAddr != nil {
		if err := eRABAdmittedItem.ULTransportLayerAddr.MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if eRABAdmittedItem.ULGTPTEID != nil {
		if err := (*eRABAdmittedItem.ULGTPTEID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (eRABAdmittedItem *ERABAdmittedItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_DLTransportLayerAddr, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_DLGTPTEID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_ULTransportLayerAddr, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_ULGTPTEID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f7, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABAdmittedItem.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABAdmittedItem.TransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABAdmittedItem.GTPTEID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_DLTransportLayerAddr {
		if err := (&eRABAdmittedItem.DLTransportLayerAddr).UnmarshalPER(r, enc); err != nil {
			return err
		}
	}
	if p_DLGTPTEID {
		var v GTPTEID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		eRABAdmittedItem.DLGTPTEID = &v
	}
	if p_ULTransportLayerAddr {
		if err := (&eRABAdmittedItem.ULTransportLayerAddr).UnmarshalPER(r, enc); err != nil {
			return err
		}
	}
	if p_ULGTPTEID {
		var v GTPTEID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		eRABAdmittedItem.ULGTPTEID = &v
	}
	if p_f7 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABDataForwardingItem *ERABDataForwardingItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(eRABDataForwardingItem.DLTransportLayerAddr != nil)
	w.WriteBit(eRABDataForwardingItem.DLGTPTEID != nil)
	w.WriteBit(eRABDataForwardingItem.ULTransportLayerAddr != nil)
	w.WriteBit(eRABDataForwardingItem.ULGTPTEID != nil)
	w.WriteBit(false)
	if err := eRABDataForwardingItem.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if eRABDataForwardingItem.DLTransportLayerAddr != nil {
		if err := eRABDataForwardingItem.DLTransportLayerAddr.MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if eRABDataForwardingItem.DLGTPTEID != nil {
		if err := (*eRABDataForwardingItem.DLGTPTEID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if eRABDataForwardingItem.ULTransportLayerAddr != nil {
		if err := eRABDataForwardingItem.ULTransportLayerAddr.MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if eRABDataForwardingItem.ULGTPTEID != nil {
		if err := (*eRABDataForwardingItem.ULGTPTEID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (eRABDataForwardingItem *ERABDataForwardingItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_DLTransportLayerAddr, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_DLGTPTEID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_ULTransportLayerAddr, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_ULGTPTEID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f5, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABDataForwardingItem.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_DLTransportLayerAddr {
		if err := (&eRABDataForwardingItem.DLTransportLayerAddr).UnmarshalPER(r, enc); err != nil {
			return err
		}
	}
	if p_DLGTPTEID {
		var v GTPTEID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		eRABDataForwardingItem.DLGTPTEID = &v
	}
	if p_ULTransportLayerAddr {
		if err := (&eRABDataForwardingItem.ULTransportLayerAddr).UnmarshalPER(r, enc); err != nil {
			return err
		}
	}
	if p_ULGTPTEID {
		var v GTPTEID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		eRABDataForwardingItem.ULGTPTEID = &v
	}
	if p_f5 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABItem *ERABItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := eRABItem.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABItem.Cause.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (eRABItem *ERABItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABItem.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABItem.Cause).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABLevelQoSParameters *ERABLevelQoSParameters) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(eRABLevelQoSParameters.GBR != nil)
	w.WriteBit(false)
	if err := eRABLevelQoSParameters.QCI.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABLevelQoSParameters.ARP.MarshalPER(w, enc); err != nil {
		return err
	}
	if eRABLevelQoSParameters.GBR != nil {
		if err := (*eRABLevelQoSParameters.GBR).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (eRABLevelQoSParameters *ERABLevelQoSParameters) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_GBR, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABLevelQoSParameters.QCI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABLevelQoSParameters.ARP).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_GBR {
		var v GBRQosInformation
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		eRABLevelQoSParameters.GBR = &v
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABModifyItemBearerModRes *ERABModifyItemBearerModRes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := eRABModifyItemBearerModRes.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (eRABModifyItemBearerModRes *ERABModifyItemBearerModRes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABModifyItemBearerModRes.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABReleaseItemBearerRelComp *ERABReleaseItemBearerRelComp) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := eRABReleaseItemBearerRelComp.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (eRABReleaseItemBearerRelComp *ERABReleaseItemBearerRelComp) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABReleaseItemBearerRelComp.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABSetupItemCtxtSURes *ERABSetupItemCtxtSURes) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := eRABSetupItemCtxtSURes.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABSetupItemCtxtSURes.TransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABSetupItemCtxtSURes.GTPTEID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (eRABSetupItemCtxtSURes *ERABSetupItemCtxtSURes) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABSetupItemCtxtSURes.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABSetupItemCtxtSURes.TransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABSetupItemCtxtSURes.GTPTEID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABToBeModifiedItemBearerModInd *ERABToBeModifiedItemBearerModInd) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := eRABToBeModifiedItemBearerModInd.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeModifiedItemBearerModInd.TransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeModifiedItemBearerModInd.DLGTPTEID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (eRABToBeModifiedItemBearerModInd *ERABToBeModifiedItemBearerModInd) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABToBeModifiedItemBearerModInd.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeModifiedItemBearerModInd.TransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeModifiedItemBearerModInd.DLGTPTEID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABToBeModifiedItemBearerModReq *ERABToBeModifiedItemBearerModReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := eRABToBeModifiedItemBearerModReq.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeModifiedItemBearerModReq.QoS.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeModifiedItemBearerModReq.NASPDU.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (eRABToBeModifiedItemBearerModReq *ERABToBeModifiedItemBearerModReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABToBeModifiedItemBearerModReq.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeModifiedItemBearerModReq.QoS).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeModifiedItemBearerModReq.NASPDU).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABToBeSetupItemBearerSUReq *ERABToBeSetupItemBearerSUReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := eRABToBeSetupItemBearerSUReq.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemBearerSUReq.QoS.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemBearerSUReq.TransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemBearerSUReq.GTPTEID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemBearerSUReq.NASPDU.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (eRABToBeSetupItemBearerSUReq *ERABToBeSetupItemBearerSUReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f5, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemBearerSUReq.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemBearerSUReq.QoS).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemBearerSUReq.TransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemBearerSUReq.GTPTEID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemBearerSUReq.NASPDU).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f5 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABToBeSetupItemCtxtSUReq *ERABToBeSetupItemCtxtSUReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(eRABToBeSetupItemCtxtSUReq.NASPDU != nil)
	w.WriteBit(false)
	if err := eRABToBeSetupItemCtxtSUReq.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemCtxtSUReq.QoS.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemCtxtSUReq.TransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemCtxtSUReq.GTPTEID.MarshalPER(w, enc); err != nil {
		return err
	}
	if eRABToBeSetupItemCtxtSUReq.NASPDU != nil {
		if err := eRABToBeSetupItemCtxtSUReq.NASPDU.MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (eRABToBeSetupItemCtxtSUReq *ERABToBeSetupItemCtxtSUReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_NASPDU, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f5, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemCtxtSUReq.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemCtxtSUReq.QoS).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemCtxtSUReq.TransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemCtxtSUReq.GTPTEID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_NASPDU {
		if err := (&eRABToBeSetupItemCtxtSUReq.NASPDU).UnmarshalPER(r, enc); err != nil {
			return err
		}
	}
	if p_f5 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABToBeSetupItemHOReq *ERABToBeSetupItemHOReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(eRABToBeSetupItemHOReq.Extensions != nil)
	if err := eRABToBeSetupItemHOReq.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemHOReq.TransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemHOReq.GTPTEID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSetupItemHOReq.QoS.MarshalPER(w, enc); err != nil {
		return err
	}
	if eRABToBeSetupItemHOReq.Extensions != nil {
		if err := (*eRABToBeSetupItemHOReq.Extensions).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (eRABToBeSetupItemHOReq *ERABToBeSetupItemHOReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_Extensions, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemHOReq.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemHOReq.TransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemHOReq.GTPTEID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSetupItemHOReq.QoS).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_Extensions {
		var v ERABToBeSetupItemHOReqExtIEs
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		eRABToBeSetupItemHOReq.Extensions = &v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (eRABToBeSwitchedDLItem *ERABToBeSwitchedDLItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := eRABToBeSwitchedDLItem.ERABID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSwitchedDLItem.TransportLayerAddress.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := eRABToBeSwitchedDLItem.GTPTEID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (eRABToBeSwitchedDLItem *ERABToBeSwitchedDLItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&eRABToBeSwitchedDLItem.ERABID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSwitchedDLItem.TransportLayerAddress).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&eRABToBeSwitchedDLItem.GTPTEID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (fiveGSTAI *FiveGSTAI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := fiveGSTAI.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := fiveGSTAI.TAC.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (fiveGSTAI *FiveGSTAI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&fiveGSTAI.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&fiveGSTAI.TAC).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (gBRQosInformation *GBRQosInformation) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := gBRQosInformation.MaximumBitrateDL.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gBRQosInformation.MaximumBitrateUL.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gBRQosInformation.GuaranteedBitrateDL.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gBRQosInformation.GuaranteedBitrateUL.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (gBRQosInformation *GBRQosInformation) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f4, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&gBRQosInformation.MaximumBitrateDL).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gBRQosInformation.MaximumBitrateUL).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gBRQosInformation.GuaranteedBitrateDL).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gBRQosInformation.GuaranteedBitrateUL).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f4 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (gNB *GNB) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := gNB.GlobalGNBID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (gNB *GNB) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&gNB.GlobalGNBID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (gUMMEI *GUMMEI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := gUMMEI.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gUMMEI.MMEGroupID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := gUMMEI.MMECode.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (gUMMEI *GUMMEI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&gUMMEI.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gUMMEI.MMEGroupID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&gUMMEI.MMECode).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (globalENBID *GlobalENBID) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := globalENBID.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := globalENBID.ENBID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (globalENBID *GlobalENBID) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&globalENBID.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&globalENBID.ENBID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (globalGNBID *GlobalGNBID) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := globalGNBID.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := globalGNBID.GNBID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (globalGNBID *GlobalGNBID) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&globalGNBID.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&globalGNBID.GNBID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (ngENB *NgENB) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := ngENB.GlobalNgENBID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (ngENB *NgENB) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&ngENB.GlobalNgENBID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (requestType *RequestType) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := encodeRootEnumerated(w, enc, 3, int64(requestType.EventType), "EventType"); err != nil {
		return err
	}
	if err := encodeRootEnumerated(w, enc, 1, int64(requestType.ReportArea), "ReportArea"); err != nil {
		return err
	}
	return nil
}

func (requestType *RequestType) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	e0, err := decodeRootEnumerated(r, enc, 3, "EventType")
	if err != nil {
		return err
	}
	requestType.EventType = EventType(e0)
	e1, err := decodeRootEnumerated(r, enc, 1, "ReportArea")
	if err != nil {
		return err
	}
	requestType.ReportArea = ReportArea(e1)
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (sTMSI *STMSI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := sTMSI.MMEC.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := sTMSI.MTMSI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (sTMSI *STMSI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&sTMSI.MMEC).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&sTMSI.MTMSI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (securityContext *SecurityContext) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 7, HasUB: true}, int64(securityContext.NextHopChainingCount)); err != nil {
		return err
	}
	if err := securityContext.NextHopParameter.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (securityContext *SecurityContext) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	n0, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 7, HasUB: true})
	if err != nil {
		return err
	}
	securityContext.NextHopChainingCount = uint8(n0)
	if err := (&securityContext.NextHopParameter).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (servedGUMMEIsItem *ServedGUMMEIsItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	off0 := 0
	if err := per.EncodeLength(w, enc, 1, 32, true, int64(len(servedGUMMEIsItem.ServedPLMNs)), func(count int64) error {
		end := off0 + int(count)
		for i := off0; i < end; i++ {
			if err := servedGUMMEIsItem.ServedPLMNs[i].MarshalPER(w, enc); err != nil {
				return err
			}
		}
		off0 = end
		return nil
	}); err != nil {
		return err
	}
	off1 := 0
	if err := per.EncodeLength(w, enc, 1, 65535, true, int64(len(servedGUMMEIsItem.ServedGroupIDs)), func(count int64) error {
		end := off1 + int(count)
		for i := off1; i < end; i++ {
			if err := servedGUMMEIsItem.ServedGroupIDs[i].MarshalPER(w, enc); err != nil {
				return err
			}
		}
		off1 = end
		return nil
	}); err != nil {
		return err
	}
	off2 := 0
	if err := per.EncodeLength(w, enc, 1, 256, true, int64(len(servedGUMMEIsItem.ServedMMECs)), func(count int64) error {
		end := off2 + int(count)
		for i := off2; i < end; i++ {
			if err := servedGUMMEIsItem.ServedMMECs[i].MarshalPER(w, enc); err != nil {
				return err
			}
		}
		off2 = end
		return nil
	}); err != nil {
		return err
	}
	return nil
}

func (servedGUMMEIsItem *ServedGUMMEIsItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f3, err := r.ReadBit()
	if err != nil {
		return err
	}
	servedGUMMEIsItem.ServedPLMNs = nil
	if err := per.DecodeLength(r, enc, 1, 32, true, func(count int64) error {
		start := len(servedGUMMEIsItem.ServedPLMNs)
		servedGUMMEIsItem.ServedPLMNs = append(servedGUMMEIsItem.ServedPLMNs, make([]PLMNIdentity, count)...)
		for i := int64(0); i < count; i++ {
			if err := (&servedGUMMEIsItem.ServedPLMNs[start+int(i)]).UnmarshalPER(r, enc); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return err
	}
	servedGUMMEIsItem.ServedGroupIDs = nil
	if err := per.DecodeLength(r, enc, 1, 65535, true, func(count int64) error {
		start := len(servedGUMMEIsItem.ServedGroupIDs)
		servedGUMMEIsItem.ServedGroupIDs = append(servedGUMMEIsItem.ServedGroupIDs, make([]MMEGroupID, count)...)
		for i := int64(0); i < count; i++ {
			if err := (&servedGUMMEIsItem.ServedGroupIDs[start+int(i)]).UnmarshalPER(r, enc); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return err
	}
	servedGUMMEIsItem.ServedMMECs = nil
	if err := per.DecodeLength(r, enc, 1, 256, true, func(count int64) error {
		start := len(servedGUMMEIsItem.ServedMMECs)
		servedGUMMEIsItem.ServedMMECs = append(servedGUMMEIsItem.ServedMMECs, make([]MMECode, count)...)
		for i := int64(0); i < count; i++ {
			if err := (&servedGUMMEIsItem.ServedMMECs[start+int(i)]).UnmarshalPER(r, enc); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return err
	}
	if p_f3 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (supportedTAItem *SupportedTAItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := supportedTAItem.TAC.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := supportedTAItem.BroadcastPLMNs.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (supportedTAItem *SupportedTAItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&supportedTAItem.TAC).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&supportedTAItem.BroadcastPLMNs).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (tAI *TAI) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := tAI.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := tAI.TAC.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (tAI *TAI) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&tAI.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&tAI.TAC).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (targetNgRanNodeID *TargetNgRanNodeID) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := targetNgRanNodeID.GlobalRANNodeID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := targetNgRanNodeID.SelectedTAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (targetNgRanNodeID *TargetNgRanNodeID) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&targetNgRanNodeID.GlobalRANNodeID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&targetNgRanNodeID.SelectedTAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (targeteNBID *TargeteNBID) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := targeteNBID.GlobalENBID.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := targeteNBID.SelectedTAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (targeteNBID *TargeteNBID) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&targeteNBID.GlobalENBID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&targeteNBID.SelectedTAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (uEAggregateMaximumBitRate *UEAggregateMaximumBitRate) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := uEAggregateMaximumBitRate.DL.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := uEAggregateMaximumBitRate.UL.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (uEAggregateMaximumBitRate *UEAggregateMaximumBitRate) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&uEAggregateMaximumBitRate.DL).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&uEAggregateMaximumBitRate.UL).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (uEAssociatedLogicalS1ConnectionItem *UEAssociatedLogicalS1ConnectionItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(uEAssociatedLogicalS1ConnectionItem.MMEUES1APID != nil)
	w.WriteBit(uEAssociatedLogicalS1ConnectionItem.ENBUES1APID != nil)
	w.WriteBit(false)
	if uEAssociatedLogicalS1ConnectionItem.MMEUES1APID != nil {
		if err := (*uEAssociatedLogicalS1ConnectionItem.MMEUES1APID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	if uEAssociatedLogicalS1ConnectionItem.ENBUES1APID != nil {
		if err := (*uEAssociatedLogicalS1ConnectionItem.ENBUES1APID).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (uEAssociatedLogicalS1ConnectionItem *UEAssociatedLogicalS1ConnectionItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_MMEUES1APID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_ENBUES1APID, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if p_MMEUES1APID {
		var v MMEUES1APID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		uEAssociatedLogicalS1ConnectionItem.MMEUES1APID = &v
	}
	if p_ENBUES1APID {
		var v ENBUES1APID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		uEAssociatedLogicalS1ConnectionItem.ENBUES1APID = &v
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (userLocationInformation *UserLocationInformation) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := userLocationInformation.EUTRANCGI.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := userLocationInformation.TAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (userLocationInformation *UserLocationInformation) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&userLocationInformation.EUTRANCGI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&userLocationInformation.TAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (erabModifyItemBearerModConf *erabModifyItemBearerModConf) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := erabModifyItemBearerModConf.erabID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (erabModifyItemBearerModConf *erabModifyItemBearerModConf) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&erabModifyItemBearerModConf.erabID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (taiItem *taiItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := taiItem.TAI.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (taiItem *taiItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f1, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&taiItem.TAI).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f1 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits = append(extBits, b)
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}
