// Code generated by pergen. DO NOT EDIT.

//go:build !ignore

package s1ap

import "github.com/ellanetworks/core/per"

func (globalENBID *GlobalENBID) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := globalENBID.PLMNIdentity.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := globalENBID.ENBID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (globalENBID *GlobalENBID) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&globalENBID.PLMNIdentity).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&globalENBID.ENBID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}

func (supportedTAItem *SupportedTAItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(false)
	w.WriteBit(false)
	if err := supportedTAItem.TAC.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := supportedTAItem.BroadcastPLMNs.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (supportedTAItem *SupportedTAItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	extBit, err := r.ReadBit()
	if err != nil {
		return err
	}
	p_f2, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&supportedTAItem.TAC).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&supportedTAItem.BroadcastPLMNs).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_f2 {
		var v ieExtensions
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		_ = v
	}
	if extBit {
		var extBits []bool
		if err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {
			extBits = make([]bool, count)
			for i := int64(0); i < count; i++ {
				b, err := r.ReadBit()
				if err != nil {
					return err
				}
				extBits[i] = b
			}
			return nil
		}); err != nil {
			return err
		}
		for _, present := range extBits {
			if !present {
				continue
			}
			if err := per.SkipOpenType(r, enc); err != nil {
				return err
			}
		}
	}
	return nil
}
