// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type N3N6EntrypointTcFiveTuple struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint16
	Pad   uint16
}

type N3N6EntrypointTcFlow struct {
	_              structs.HostLayout
	Imsi           uint64
	Saddr          N3N6EntrypointTcIn6Addr
	Daddr          N3N6EntrypointTcIn6Addr
	IngressIfindex uint32
	EgressIfindex  uint32
	Sport          uint16
	Dport          uint16
	Proto          uint8
	Dscp           uint8
	Action         uint8
	_              [1]byte
}

type N3N6EntrypointTcFlowStats struct {
	_       structs.HostLayout
	FirstTs uint64
	LastTs  uint64
	Bytes   uint64
	Packets uint64
}

type N3N6EntrypointTcFramedIp4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type N3N6EntrypointTcFramedIp6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      N3N6EntrypointTcIn6Addr
}

type N3N6EntrypointTcIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type N3N6EntrypointTcNatEntry struct {
	_         structs.HostLayout
	Peer      N3N6EntrypointTcFiveTuple
	RefreshTs uint64
	State     uint8
	Replied   uint8
	UeSide    uint8
	Closed    uint8
	Pad       [4]uint8
}

type N3N6EntrypointTcPdrInfo struct {
	_                  structs.HostLayout
	LocalSeid          uint64
	Imsi               uint64
	PdrId              uint32
	UrrId              uint32
	OuterHeaderRemoval uint8
	Pad                [3]uint8
	Far                struct {
		_                     structs.HostLayout
		Action                uint8
		OuterHeaderCreation   uint8
		_                     [2]byte
		Teid                  uint32
		Remoteip              N3N6EntrypointTcIn6Addr
		Localip               N3N6EntrypointTcIn6Addr
		TransportLevelMarking uint16
		_                     [2]byte
	}
	Qer struct {
		_                structs.HostLayout
		UlGateStatus     uint8
		DlGateStatus     uint8
		Qfi              uint8
		_                [5]byte
		UlMaximumBitrate uint64
		DlMaximumBitrate uint64
		UlStart          uint64
		DlStart          uint64
	}
	FilterMapIndex uint32
	UeIpv4         N3N6EntrypointTcIn6Addr
	UeIpv6         N3N6EntrypointTcIn6Addr
	_              [4]byte
}

type N3N6EntrypointTcRouteStat struct {
	_                       structs.HostLayout
	FibLookupIp4Cache       uint64
	FibLookupIp4Success     uint64
	FibLookupIp4NoNeigh     uint64
	FibLookupIp4Blackhole   uint64
	FibLookupIp4Unreachable uint64
	FibLookupIp4Prohibit    uint64
	FibLookupIp4NoSrcAddr   uint64
	FibLookupIp4FragNeeded  uint64
	FibLookupIp4NotFwded    uint64
	FibLookupIp4FwdDisabled uint64
	FibLookupIp4UnsuppLwt   uint64
	Ip4IfindexMismatch      uint64
	FibLookupIp6Cache       uint64
	FibLookupIp6Success     uint64
	FibLookupIp6NoNeigh     uint64
	FibLookupIp6Blackhole   uint64
	FibLookupIp6Unreachable uint64
	FibLookupIp6Prohibit    uint64
	FibLookupIp6NoSrcAddr   uint64
	FibLookupIp6FragNeeded  uint64
	FibLookupIp6NotFwded    uint64
	FibLookupIp6FwdDisabled uint64
	FibLookupIp6UnsuppLwt   uint64
	Ip6IfindexMismatch      uint64
	FibLookupIp4Error       uint64
	FibLookupIp6Error       uint64
}

type N3N6EntrypointTcSdfFilterList struct {
	_        structs.HostLayout
	NumRules uint8
	Pad      [3]uint8
	Rules    [12]struct {
		_         structs.HostLayout
		RemoteIp  N3N6EntrypointTcIn6Addr
		PrefixLen uint8
		_         [1]byte
		PortLow   uint16
		PortHigh  uint16
		Protocol  uint8
		Action    uint8
		Pad       [7]uint8
		_         [1]byte
	}
}

type N3N6EntrypointTcUpfStatistic struct {
	_           structs.HostLayout
	ByteCounter struct {
		_     structs.HostLayout
		Bytes uint64
	}
	PacketCounters struct {
		_  structs.HostLayout
		Rx uint64
		Tx uint64
	}
	ForwardedActions [8]uint64
	DropReasons      [64]uint64
}

type N3N6EntrypointTcUrrKey struct {
	_     structs.HostLayout
	Seid  uint64
	UrrId uint32
	Pad   uint32
}

type N3N6EntrypointTcVethTunnelInfo struct {
	_          structs.HostLayout
	Teid       uint32
	LocalAddr  N3N6EntrypointTcIn6Addr
	RemoteAddr N3N6EntrypointTcIn6Addr
	Qfi        uint8
	NoPsc      uint8
	Pad        [2]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	N3N6EntrypointTcMapCsumScratch         = "csum_scratch"
	N3N6EntrypointTcMapDownlinkRouteStats  = "downlink_route_stats"
	N3N6EntrypointTcMapDownlinkStatistics  = "downlink_statistics"
	N3N6EntrypointTcMapFlowStats           = "flow_stats"
	N3N6EntrypointTcMapFramedDownlinkIp4   = "framed_downlink_ip4"
	N3N6EntrypointTcMapFramedDownlinkIp6   = "framed_downlink_ip6"
	N3N6EntrypointTcMapNatCt               = "nat_ct"
	N3N6EntrypointTcMapNoNeighMap          = "no_neigh_map"
	N3N6EntrypointTcMapNocpMap             = "nocp_map"
	N3N6EntrypointTcMapPdrsDownlinkIp4     = "pdrs_downlink_ip4"
	N3N6EntrypointTcMapPdrsDownlinkIp6     = "pdrs_downlink_ip6"
	N3N6EntrypointTcMapPdrsUplink          = "pdrs_uplink"
	N3N6EntrypointTcMapRsEventMap          = "rs_event_map"
	N3N6EntrypointTcMapSdfFilters          = "sdf_filters"
	N3N6EntrypointTcMapUpfCalls            = "upf_calls"
	N3N6EntrypointTcMapUplinkRouteStats    = "uplink_route_stats"
	N3N6EntrypointTcMapUplinkStatistics    = "uplink_statistics"
	N3N6EntrypointTcMapUrrMap              = "urr_map"
	N3N6EntrypointTcMapVethTunnels         = "veth_tunnels"
	N3N6EntrypointTcProgUpfDownlinkFunc    = "upf_downlink_func"
	N3N6EntrypointTcProgUpfEntryFunc       = "upf_entry_func"
	N3N6EntrypointTcProgUpfGtpuControlFunc = "upf_gtpu_control_func"
	N3N6EntrypointTcProgUpfUplinkFunc      = "upf_uplink_func"
	N3N6EntrypointTcProgVethXdpFunc        = "veth_xdp_func"
	N3N6EntrypointTcVarFlowact             = "flowact"
	N3N6EntrypointTcVarMasquerade          = "masquerade"
	N3N6EntrypointTcVarN3Ifindex           = "n3_ifindex"
	N3N6EntrypointTcVarN3Vlan              = "n3_vlan"
	N3N6EntrypointTcVarN6Ifindex           = "n6_ifindex"
	N3N6EntrypointTcVarN6Vlan              = "n6_vlan"
	N3N6EntrypointTcVarNatPortMax          = "nat_port_max"
	N3N6EntrypointTcVarNatPortMin          = "nat_port_min"
)

// LoadN3N6EntrypointTc returns the embedded CollectionSpec for N3N6EntrypointTc.
func LoadN3N6EntrypointTc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_N3N6EntrypointTcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load N3N6EntrypointTc: %w", err)
	}

	return spec, err
}

// LoadN3N6EntrypointTcObjects loads N3N6EntrypointTc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*N3N6EntrypointTcObjects
//	*N3N6EntrypointTcPrograms
//	*N3N6EntrypointTcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadN3N6EntrypointTcObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadN3N6EntrypointTc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// N3N6EntrypointTcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type N3N6EntrypointTcSpecs struct {
	N3N6EntrypointTcProgramSpecs
	N3N6EntrypointTcMapSpecs
	N3N6EntrypointTcVariableSpecs
}

// N3N6EntrypointTcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type N3N6EntrypointTcProgramSpecs struct {
	UpfDownlinkFunc    *ebpf.ProgramSpec `ebpf:"upf_downlink_func"`
	UpfEntryFunc       *ebpf.ProgramSpec `ebpf:"upf_entry_func"`
	UpfGtpuControlFunc *ebpf.ProgramSpec `ebpf:"upf_gtpu_control_func"`
	UpfUplinkFunc      *ebpf.ProgramSpec `ebpf:"upf_uplink_func"`
	VethXdpFunc        *ebpf.ProgramSpec `ebpf:"veth_xdp_func"`
}

// N3N6EntrypointTcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type N3N6EntrypointTcMapSpecs struct {
	CsumScratch        *ebpf.MapSpec `ebpf:"csum_scratch"`
	DownlinkRouteStats *ebpf.MapSpec `ebpf:"downlink_route_stats"`
	DownlinkStatistics *ebpf.MapSpec `ebpf:"downlink_statistics"`
	FlowStats          *ebpf.MapSpec `ebpf:"flow_stats"`
	FramedDownlinkIp4  *ebpf.MapSpec `ebpf:"framed_downlink_ip4"`
	FramedDownlinkIp6  *ebpf.MapSpec `ebpf:"framed_downlink_ip6"`
	NatCt              *ebpf.MapSpec `ebpf:"nat_ct"`
	NoNeighMap         *ebpf.MapSpec `ebpf:"no_neigh_map"`
	NocpMap            *ebpf.MapSpec `ebpf:"nocp_map"`
	PdrsDownlinkIp4    *ebpf.MapSpec `ebpf:"pdrs_downlink_ip4"`
	PdrsDownlinkIp6    *ebpf.MapSpec `ebpf:"pdrs_downlink_ip6"`
	PdrsUplink         *ebpf.MapSpec `ebpf:"pdrs_uplink"`
	RsEventMap         *ebpf.MapSpec `ebpf:"rs_event_map"`
	SdfFilters         *ebpf.MapSpec `ebpf:"sdf_filters"`
	UpfCalls           *ebpf.MapSpec `ebpf:"upf_calls"`
	UplinkRouteStats   *ebpf.MapSpec `ebpf:"uplink_route_stats"`
	UplinkStatistics   *ebpf.MapSpec `ebpf:"uplink_statistics"`
	UrrMap             *ebpf.MapSpec `ebpf:"urr_map"`
	VethTunnels        *ebpf.MapSpec `ebpf:"veth_tunnels"`
}

// N3N6EntrypointTcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type N3N6EntrypointTcVariableSpecs struct {
	Flowact    *ebpf.VariableSpec `ebpf:"flowact"`
	Masquerade *ebpf.VariableSpec `ebpf:"masquerade"`
	N3Ifindex  *ebpf.VariableSpec `ebpf:"n3_ifindex"`
	N3Vlan     *ebpf.VariableSpec `ebpf:"n3_vlan"`
	N6Ifindex  *ebpf.VariableSpec `ebpf:"n6_ifindex"`
	N6Vlan     *ebpf.VariableSpec `ebpf:"n6_vlan"`
	NatPortMax *ebpf.VariableSpec `ebpf:"nat_port_max"`
	NatPortMin *ebpf.VariableSpec `ebpf:"nat_port_min"`
}

// N3N6EntrypointTcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadN3N6EntrypointTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type N3N6EntrypointTcObjects struct {
	N3N6EntrypointTcPrograms
	N3N6EntrypointTcMaps
	N3N6EntrypointTcVariables
}

func (o *N3N6EntrypointTcObjects) Close() error {
	return _N3N6EntrypointTcClose(
		&o.N3N6EntrypointTcPrograms,
		&o.N3N6EntrypointTcMaps,
	)
}

// N3N6EntrypointTcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadN3N6EntrypointTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type N3N6EntrypointTcMaps struct {
	CsumScratch        *ebpf.Map `ebpf:"csum_scratch"`
	DownlinkRouteStats *ebpf.Map `ebpf:"downlink_route_stats"`
	DownlinkStatistics *ebpf.Map `ebpf:"downlink_statistics"`
	FlowStats          *ebpf.Map `ebpf:"flow_stats"`
	FramedDownlinkIp4  *ebpf.Map `ebpf:"framed_downlink_ip4"`
	FramedDownlinkIp6  *ebpf.Map `ebpf:"framed_downlink_ip6"`
	NatCt              *ebpf.Map `ebpf:"nat_ct"`
	NoNeighMap         *ebpf.Map `ebpf:"no_neigh_map"`
	NocpMap            *ebpf.Map `ebpf:"nocp_map"`
	PdrsDownlinkIp4    *ebpf.Map `ebpf:"pdrs_downlink_ip4"`
	PdrsDownlinkIp6    *ebpf.Map `ebpf:"pdrs_downlink_ip6"`
	PdrsUplink         *ebpf.Map `ebpf:"pdrs_uplink"`
	RsEventMap         *ebpf.Map `ebpf:"rs_event_map"`
	SdfFilters         *ebpf.Map `ebpf:"sdf_filters"`
	UpfCalls           *ebpf.Map `ebpf:"upf_calls"`
	UplinkRouteStats   *ebpf.Map `ebpf:"uplink_route_stats"`
	UplinkStatistics   *ebpf.Map `ebpf:"uplink_statistics"`
	UrrMap             *ebpf.Map `ebpf:"urr_map"`
	VethTunnels        *ebpf.Map `ebpf:"veth_tunnels"`
}

func (m *N3N6EntrypointTcMaps) Close() error {
	return _N3N6EntrypointTcClose(
		m.CsumScratch,
		m.DownlinkRouteStats,
		m.DownlinkStatistics,
		m.FlowStats,
		m.FramedDownlinkIp4,
		m.FramedDownlinkIp6,
		m.NatCt,
		m.NoNeighMap,
		m.NocpMap,
		m.PdrsDownlinkIp4,
		m.PdrsDownlinkIp6,
		m.PdrsUplink,
		m.RsEventMap,
		m.SdfFilters,
		m.UpfCalls,
		m.UplinkRouteStats,
		m.UplinkStatistics,
		m.UrrMap,
		m.VethTunnels,
	)
}

// N3N6EntrypointTcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadN3N6EntrypointTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type N3N6EntrypointTcVariables struct {
	Flowact    *ebpf.Variable `ebpf:"flowact"`
	Masquerade *ebpf.Variable `ebpf:"masquerade"`
	N3Ifindex  *ebpf.Variable `ebpf:"n3_ifindex"`
	N3Vlan     *ebpf.Variable `ebpf:"n3_vlan"`
	N6Ifindex  *ebpf.Variable `ebpf:"n6_ifindex"`
	N6Vlan     *ebpf.Variable `ebpf:"n6_vlan"`
	NatPortMax *ebpf.Variable `ebpf:"nat_port_max"`
	NatPortMin *ebpf.Variable `ebpf:"nat_port_min"`
}

// N3N6EntrypointTcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadN3N6EntrypointTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type N3N6EntrypointTcPrograms struct {
	UpfDownlinkFunc    *ebpf.Program `ebpf:"upf_downlink_func"`
	UpfEntryFunc       *ebpf.Program `ebpf:"upf_entry_func"`
	UpfGtpuControlFunc *ebpf.Program `ebpf:"upf_gtpu_control_func"`
	UpfUplinkFunc      *ebpf.Program `ebpf:"upf_uplink_func"`
	VethXdpFunc        *ebpf.Program `ebpf:"veth_xdp_func"`
}

func (p *N3N6EntrypointTcPrograms) Close() error {
	return _N3N6EntrypointTcClose(
		p.UpfDownlinkFunc,
		p.UpfEntryFunc,
		p.UpfGtpuControlFunc,
		p.UpfUplinkFunc,
		p.VethXdpFunc,
	)
}

func _N3N6EntrypointTcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed n3n6entrypointtc_bpf.o
var _N3N6EntrypointTcBytes []byte
