// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type N3N6EntrypointFarInfo struct {
	_                     structs.HostLayout
	Action                uint8
	OuterHeaderCreation   uint8
	_                     [2]byte
	Teid                  uint32
	Remoteip              uint32
	Localip               uint32
	TransportLevelMarking uint16
	_                     [2]byte
}

type N3N6EntrypointFiveTuple struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint16
	_     [2]byte
}

type N3N6EntrypointIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type N3N6EntrypointNatEntry struct {
	_         structs.HostLayout
	Src       N3N6EntrypointFiveTuple
	RefreshTs uint64
}

type N3N6EntrypointPdrInfo struct {
	_                  structs.HostLayout
	LocalSeid          uint64
	PdrId              uint32
	FarId              uint32
	QerId              uint32
	OuterHeaderRemoval uint8
	SdfMode            uint8
	_                  [10]byte
	SdfRules           struct {
		_         structs.HostLayout
		SdfFilter struct {
			_       structs.HostLayout
			SrcAddr struct {
				_    structs.HostLayout
				Type uint8
				_    [15]byte
				Ip   [16]byte /* uint128 */
				Mask [16]byte /* uint128 */
			}
			DstAddr struct {
				_    structs.HostLayout
				Type uint8
				_    [15]byte
				Ip   [16]byte /* uint128 */
				Mask [16]byte /* uint128 */
			}
			SrcPort struct {
				_          structs.HostLayout
				LowerBound uint16
				UpperBound uint16
			}
			DstPort struct {
				_          structs.HostLayout
				LowerBound uint16
				UpperBound uint16
			}
			Protocol uint8
			_        [7]byte
		}
		OuterHeaderRemoval uint8
		_                  [3]byte
		FarId              uint32
		QerId              uint32
		_                  [4]byte
	}
}

type N3N6EntrypointQerInfo struct {
	_                structs.HostLayout
	UlGateStatus     uint8
	DlGateStatus     uint8
	Qfi              uint8
	_                [1]byte
	UlMaximumBitrate uint32
	DlMaximumBitrate uint32
	_                [4]byte
	UlStart          uint64
	DlStart          uint64
}

type N3N6EntrypointRouteStat struct {
	_                     structs.HostLayout
	FibLookupIp4Cache     uint64
	FibLookupIp4Ok        uint64
	FibLookupIp4ErrorDrop uint64
	FibLookupIp4ErrorPass uint64
	FibLookupIp6Cache     uint64
	FibLookupIp6Ok        uint64
	FibLookupIp6ErrorDrop uint64
	FibLookupIp6ErrorPass uint64
}

type N3N6EntrypointUpfStatistic struct {
	_           structs.HostLayout
	ByteCounter struct {
		_     structs.HostLayout
		Bytes uint64
	}
	PacketCounters struct {
		_  structs.HostLayout
		Rx uint64
		Tx uint64
	}
	XdpActions [8]uint64
}

// LoadN3N6Entrypoint returns the embedded CollectionSpec for N3N6Entrypoint.
func LoadN3N6Entrypoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_N3N6EntrypointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load N3N6Entrypoint: %w", err)
	}

	return spec, err
}

// LoadN3N6EntrypointObjects loads N3N6Entrypoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*N3N6EntrypointObjects
//	*N3N6EntrypointPrograms
//	*N3N6EntrypointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadN3N6EntrypointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadN3N6Entrypoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// N3N6EntrypointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type N3N6EntrypointSpecs struct {
	N3N6EntrypointProgramSpecs
	N3N6EntrypointMapSpecs
	N3N6EntrypointVariableSpecs
}

// N3N6EntrypointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type N3N6EntrypointProgramSpecs struct {
	UpfN3N6EntrypointFunc *ebpf.ProgramSpec `ebpf:"upf_n3_n6_entrypoint_func"`
}

// N3N6EntrypointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type N3N6EntrypointMapSpecs struct {
	DownlinkRouteStats *ebpf.MapSpec `ebpf:"downlink_route_stats"`
	DownlinkStatistics *ebpf.MapSpec `ebpf:"downlink_statistics"`
	FarMap             *ebpf.MapSpec `ebpf:"far_map"`
	NatCt              *ebpf.MapSpec `ebpf:"nat_ct"`
	NocpMap            *ebpf.MapSpec `ebpf:"nocp_map"`
	PdrsDownlinkIp4    *ebpf.MapSpec `ebpf:"pdrs_downlink_ip4"`
	PdrsDownlinkIp6    *ebpf.MapSpec `ebpf:"pdrs_downlink_ip6"`
	PdrsUplink         *ebpf.MapSpec `ebpf:"pdrs_uplink"`
	QerMap             *ebpf.MapSpec `ebpf:"qer_map"`
	UplinkRouteStats   *ebpf.MapSpec `ebpf:"uplink_route_stats"`
	UplinkStatistics   *ebpf.MapSpec `ebpf:"uplink_statistics"`
}

// N3N6EntrypointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type N3N6EntrypointVariableSpecs struct {
	Masquerade *ebpf.VariableSpec `ebpf:"masquerade"`
	N3Ifindex  *ebpf.VariableSpec `ebpf:"n3_ifindex"`
	N3Vlan     *ebpf.VariableSpec `ebpf:"n3_vlan"`
	N6Ifindex  *ebpf.VariableSpec `ebpf:"n6_ifindex"`
	N6Vlan     *ebpf.VariableSpec `ebpf:"n6_vlan"`
}

// N3N6EntrypointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadN3N6EntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type N3N6EntrypointObjects struct {
	N3N6EntrypointPrograms
	N3N6EntrypointMaps
	N3N6EntrypointVariables
}

func (o *N3N6EntrypointObjects) Close() error {
	return _N3N6EntrypointClose(
		&o.N3N6EntrypointPrograms,
		&o.N3N6EntrypointMaps,
	)
}

// N3N6EntrypointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadN3N6EntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type N3N6EntrypointMaps struct {
	DownlinkRouteStats *ebpf.Map `ebpf:"downlink_route_stats"`
	DownlinkStatistics *ebpf.Map `ebpf:"downlink_statistics"`
	FarMap             *ebpf.Map `ebpf:"far_map"`
	NatCt              *ebpf.Map `ebpf:"nat_ct"`
	NocpMap            *ebpf.Map `ebpf:"nocp_map"`
	PdrsDownlinkIp4    *ebpf.Map `ebpf:"pdrs_downlink_ip4"`
	PdrsDownlinkIp6    *ebpf.Map `ebpf:"pdrs_downlink_ip6"`
	PdrsUplink         *ebpf.Map `ebpf:"pdrs_uplink"`
	QerMap             *ebpf.Map `ebpf:"qer_map"`
	UplinkRouteStats   *ebpf.Map `ebpf:"uplink_route_stats"`
	UplinkStatistics   *ebpf.Map `ebpf:"uplink_statistics"`
}

func (m *N3N6EntrypointMaps) Close() error {
	return _N3N6EntrypointClose(
		m.DownlinkRouteStats,
		m.DownlinkStatistics,
		m.FarMap,
		m.NatCt,
		m.NocpMap,
		m.PdrsDownlinkIp4,
		m.PdrsDownlinkIp6,
		m.PdrsUplink,
		m.QerMap,
		m.UplinkRouteStats,
		m.UplinkStatistics,
	)
}

// N3N6EntrypointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadN3N6EntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type N3N6EntrypointVariables struct {
	Masquerade *ebpf.Variable `ebpf:"masquerade"`
	N3Ifindex  *ebpf.Variable `ebpf:"n3_ifindex"`
	N3Vlan     *ebpf.Variable `ebpf:"n3_vlan"`
	N6Ifindex  *ebpf.Variable `ebpf:"n6_ifindex"`
	N6Vlan     *ebpf.Variable `ebpf:"n6_vlan"`
}

// N3N6EntrypointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadN3N6EntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type N3N6EntrypointPrograms struct {
	UpfN3N6EntrypointFunc *ebpf.Program `ebpf:"upf_n3_n6_entrypoint_func"`
}

func (p *N3N6EntrypointPrograms) Close() error {
	return _N3N6EntrypointClose(
		p.UpfN3N6EntrypointFunc,
	)
}

func _N3N6EntrypointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed n3n6entrypoint_bpf.o
var _N3N6EntrypointBytes []byte
