// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type VethEntrypointFiveTuple struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint16
	_     [2]byte
}

type VethEntrypointFlow struct {
	_              structs.HostLayout
	Imsi           uint64
	Saddr          uint32
	Daddr          uint32
	IngressIfindex uint32
	EgressIfindex  uint32
	Sport          uint16
	Dport          uint16
	Proto          uint8
	Tos            uint8
	Action         uint8
	_              [1]byte
}

type VethEntrypointFlowStats struct {
	_       structs.HostLayout
	FirstTs uint64
	LastTs  uint64
	Bytes   uint64
	Packets uint64
}

type VethEntrypointIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type VethEntrypointNatEntry struct {
	_         structs.HostLayout
	Src       VethEntrypointFiveTuple
	RefreshTs uint64
}

type VethEntrypointPdrInfo struct {
	_                  structs.HostLayout
	LocalSeid          uint64
	Imsi               uint64
	PdrId              uint32
	UrrId              uint32
	OuterHeaderRemoval uint8
	Pad                [3]uint8
	Far                struct {
		_                     structs.HostLayout
		Action                uint8
		OuterHeaderCreation   uint8
		_                     [2]byte
		Teid                  uint32
		Remoteip              VethEntrypointIn6Addr
		Localip               VethEntrypointIn6Addr
		TransportLevelMarking uint16
		_                     [2]byte
	}
	Qer struct {
		_                structs.HostLayout
		UlGateStatus     uint8
		DlGateStatus     uint8
		Qfi              uint8
		_                [5]byte
		UlMaximumBitrate uint64
		DlMaximumBitrate uint64
		UlStart          uint64
		DlStart          uint64
	}
	FilterMapIndex uint32
	_              [4]byte
}

type VethEntrypointRouteStat struct {
	_                       structs.HostLayout
	FibLookupIp4Cache       uint64
	FibLookupIp4Success     uint64
	FibLookupIp4NoNeigh     uint64
	FibLookupIp4Blackhole   uint64
	FibLookupIp4Unreachable uint64
	FibLookupIp4Prohibit    uint64
	FibLookupIp4NoSrcAddr   uint64
	FibLookupIp4FragNeeded  uint64
	FibLookupIp4NotFwded    uint64
	FibLookupIp4FwdDisabled uint64
	FibLookupIp4UnsuppLwt   uint64
	Ip4IfindexMismatch      uint64
	FibLookupIp6Cache       uint64
	FibLookupIp6Success     uint64
	FibLookupIp6NoNeigh     uint64
	FibLookupIp6Blackhole   uint64
	FibLookupIp6Unreachable uint64
	FibLookupIp6Prohibit    uint64
	FibLookupIp6NoSrcAddr   uint64
	FibLookupIp6FragNeeded  uint64
	FibLookupIp6NotFwded    uint64
	FibLookupIp6FwdDisabled uint64
	FibLookupIp6UnsuppLwt   uint64
	Ip6IfindexMismatch      uint64
}

type VethEntrypointSdfFilterList struct {
	_        structs.HostLayout
	NumRules uint8
	Pad      [3]uint8
	Rules    [12]struct {
		_          structs.HostLayout
		RemoteIp   uint32
		RemoteMask uint32
		PortLow    uint16
		PortHigh   uint16
		Protocol   uint8
		Action     uint8
		Pad        [2]uint8
	}
}

type VethEntrypointUpfStatistic struct {
	_           structs.HostLayout
	ByteCounter struct {
		_     structs.HostLayout
		Bytes uint64
	}
	PacketCounters struct {
		_  structs.HostLayout
		Rx uint64
		Tx uint64
	}
	XdpActions [8]uint64
}

type VethEntrypointVethTunnelInfo struct {
	_          structs.HostLayout
	Teid       uint32
	LocalAddr  VethEntrypointIn6Addr
	RemoteAddr VethEntrypointIn6Addr
	Qfi        uint8
	Pad        [3]uint8
}

// LoadVethEntrypoint returns the embedded CollectionSpec for VethEntrypoint.
func LoadVethEntrypoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VethEntrypointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load VethEntrypoint: %w", err)
	}

	return spec, err
}

// LoadVethEntrypointObjects loads VethEntrypoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*VethEntrypointObjects
//	*VethEntrypointPrograms
//	*VethEntrypointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadVethEntrypointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadVethEntrypoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// VethEntrypointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VethEntrypointSpecs struct {
	VethEntrypointProgramSpecs
	VethEntrypointMapSpecs
	VethEntrypointVariableSpecs
}

// VethEntrypointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VethEntrypointProgramSpecs struct {
	VethXdpFunc *ebpf.ProgramSpec `ebpf:"veth_xdp_func"`
}

// VethEntrypointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VethEntrypointMapSpecs struct {
	CsumScratch        *ebpf.MapSpec `ebpf:"csum_scratch"`
	DownlinkRouteStats *ebpf.MapSpec `ebpf:"downlink_route_stats"`
	DownlinkStatistics *ebpf.MapSpec `ebpf:"downlink_statistics"`
	FlowStats          *ebpf.MapSpec `ebpf:"flow_stats"`
	NatCt              *ebpf.MapSpec `ebpf:"nat_ct"`
	NoNeighMap         *ebpf.MapSpec `ebpf:"no_neigh_map"`
	NocpMap            *ebpf.MapSpec `ebpf:"nocp_map"`
	PdrsDownlinkIp4    *ebpf.MapSpec `ebpf:"pdrs_downlink_ip4"`
	PdrsDownlinkIp6    *ebpf.MapSpec `ebpf:"pdrs_downlink_ip6"`
	SdfFilters         *ebpf.MapSpec `ebpf:"sdf_filters"`
	UrrMap             *ebpf.MapSpec `ebpf:"urr_map"`
	VethTunnels        *ebpf.MapSpec `ebpf:"veth_tunnels"`
}

// VethEntrypointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VethEntrypointVariableSpecs struct {
	Flowact    *ebpf.VariableSpec `ebpf:"flowact"`
	Masquerade *ebpf.VariableSpec `ebpf:"masquerade"`
	N3Ifindex  *ebpf.VariableSpec `ebpf:"n3_ifindex"`
	N3Vlan     *ebpf.VariableSpec `ebpf:"n3_vlan"`
	N6Ifindex  *ebpf.VariableSpec `ebpf:"n6_ifindex"`
	N6Vlan     *ebpf.VariableSpec `ebpf:"n6_vlan"`
}

// VethEntrypointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadVethEntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type VethEntrypointObjects struct {
	VethEntrypointPrograms
	VethEntrypointMaps
	VethEntrypointVariables
}

func (o *VethEntrypointObjects) Close() error {
	return _VethEntrypointClose(
		&o.VethEntrypointPrograms,
		&o.VethEntrypointMaps,
	)
}

// VethEntrypointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadVethEntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type VethEntrypointMaps struct {
	CsumScratch        *ebpf.Map `ebpf:"csum_scratch"`
	DownlinkRouteStats *ebpf.Map `ebpf:"downlink_route_stats"`
	DownlinkStatistics *ebpf.Map `ebpf:"downlink_statistics"`
	FlowStats          *ebpf.Map `ebpf:"flow_stats"`
	NatCt              *ebpf.Map `ebpf:"nat_ct"`
	NoNeighMap         *ebpf.Map `ebpf:"no_neigh_map"`
	NocpMap            *ebpf.Map `ebpf:"nocp_map"`
	PdrsDownlinkIp4    *ebpf.Map `ebpf:"pdrs_downlink_ip4"`
	PdrsDownlinkIp6    *ebpf.Map `ebpf:"pdrs_downlink_ip6"`
	SdfFilters         *ebpf.Map `ebpf:"sdf_filters"`
	UrrMap             *ebpf.Map `ebpf:"urr_map"`
	VethTunnels        *ebpf.Map `ebpf:"veth_tunnels"`
}

func (m *VethEntrypointMaps) Close() error {
	return _VethEntrypointClose(
		m.CsumScratch,
		m.DownlinkRouteStats,
		m.DownlinkStatistics,
		m.FlowStats,
		m.NatCt,
		m.NoNeighMap,
		m.NocpMap,
		m.PdrsDownlinkIp4,
		m.PdrsDownlinkIp6,
		m.SdfFilters,
		m.UrrMap,
		m.VethTunnels,
	)
}

// VethEntrypointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadVethEntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type VethEntrypointVariables struct {
	Flowact    *ebpf.Variable `ebpf:"flowact"`
	Masquerade *ebpf.Variable `ebpf:"masquerade"`
	N3Ifindex  *ebpf.Variable `ebpf:"n3_ifindex"`
	N3Vlan     *ebpf.Variable `ebpf:"n3_vlan"`
	N6Ifindex  *ebpf.Variable `ebpf:"n6_ifindex"`
	N6Vlan     *ebpf.Variable `ebpf:"n6_vlan"`
}

// VethEntrypointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadVethEntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type VethEntrypointPrograms struct {
	VethXdpFunc *ebpf.Program `ebpf:"veth_xdp_func"`
}

func (p *VethEntrypointPrograms) Close() error {
	return _VethEntrypointClose(
		p.VethXdpFunc,
	)
}

func _VethEntrypointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed vethentrypoint_bpf.o
var _VethEntrypointBytes []byte
