apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
data:
  config.yaml: |
    logging:
      system:
        level: "debug"
        output: "stdout"
      audit:
        output: "stdout"
    db:
      path: /core/data/core.db
    interfaces:
      n2:
        address: "192.168.253.3"
        port: 38412
      n3:
        name: "n3"
        address: "192.168.252.3"
      n6:
        name: "n6"
      api:
        address: "127.0.0.1"
        port: 5002
    xdp:
      attach-mode: "generic"
