apiVersion: apps/v1
kind: Deployment
metadata:
  name: ella-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ella-core
  template:
    metadata:
      labels:
        app: ella-core
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {"name": "core-n2", "interface": "n2"},
            {"name": "core-n3", "interface": "n3"},
            {"name": "core-n6", "interface": "n6"}
          ]
    spec:
      containers:
      - name: core
        image: ghcr.io/ellanetworks/ella-core:v0.3.1
        imagePullPolicy: Always
        command: ["core"]
        args: ["--config", "/config/config.yaml"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: sysfs-bpf
          mountPath: /sys/fs/bpf
        - name: data-volume
          mountPath: /core/data
        ports:
        - containerPort: 5002
        - containerPort: 38412
      volumes:
      - name: config-volume
        configMap:
          name: core-config
      - name: data-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: sysfs-bpf
        hostPath:
          path: /sys/fs/bpf
          type: Directory
