// SPDX-FileCopyrightText: Ella Networks Inc.
// SPDX-License-Identifier: BUSL-1.1

// Code generated by pergen. DO NOT EDIT.

//go:build !ignore

package rrctest

import "github.com/ellanetworks/core/internal/per"

func (deprioritisationReq *DeprioritisationReq) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(deprioritisationReq.Extended != nil)
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 1, HasUB: true}, int64(deprioritisationReq.Type)); err != nil {
		return err
	}
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 1, HasUB: true}, int64(deprioritisationReq.Time)); err != nil {
		return err
	}
	if deprioritisationReq.Extended != nil {
		per.EncodeBoolean(w, enc, (*deprioritisationReq.Extended))
	}
	return nil
}

func (deprioritisationReq *DeprioritisationReq) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	p_Extended, err := r.ReadBit()
	if err != nil {
		return err
	}
	n0, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 1, HasUB: true})
	if err != nil {
		return err
	}
	deprioritisationReq.Type = int(n0)
	n1, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 1, HasUB: true})
	if err != nil {
		return err
	}
	deprioritisationReq.Time = int(n1)
	if p_Extended {
		var v bool
		b2, err := per.DecodeBoolean(r, enc)
		if err != nil {
			return err
		}
		v = b2
		deprioritisationReq.Extended = &v
	}
	return nil
}

func (rRCRelease *RRCRelease) MarshalPER(w *per.Writer, enc per.Encoding) error {
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 3, HasUB: true}, int64(rRCRelease.RRCTransactionID)); err != nil {
		return err
	}
	if err := rRCRelease.CriticalExtensions.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (rRCRelease *RRCRelease) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	n0, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 3, HasUB: true})
	if err != nil {
		return err
	}
	rRCRelease.RRCTransactionID = int(n0)
	if err := (&rRCRelease.CriticalExtensions).UnmarshalPER(r, enc); err != nil {
		return err
	}
	return nil
}

func (rRCReleaseIEs *RRCReleaseIEs) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(rRCReleaseIEs.Deprioritisation != nil)
	if rRCReleaseIEs.Deprioritisation != nil {
		if err := (*rRCReleaseIEs.Deprioritisation).MarshalPER(w, enc); err != nil {
			return err
		}
	}
	return nil
}

func (rRCReleaseIEs *RRCReleaseIEs) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	p_Deprioritisation, err := r.ReadBit()
	if err != nil {
		return err
	}
	if p_Deprioritisation {
		var v DeprioritisationReq
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		rRCReleaseIEs.Deprioritisation = &v
	}
	return nil
}

func (releaseChoice *ReleaseChoice) MarshalPER(w *per.Writer, enc per.Encoding) error {
	switch {
	case releaseChoice.RRCRelease != nil:
		if err := per.EncodeConstrainedWholeNumber(w, enc, 0, 1, 0); err != nil {
			return err
		}
		if err := (*releaseChoice.RRCRelease).MarshalPER(w, enc); err != nil {
			return err
		}
	case releaseChoice.Late != nil:
		if err := per.EncodeConstrainedWholeNumber(w, enc, 0, 1, 1); err != nil {
			return err
		}
		per.EncodeBoolean(w, enc, (*releaseChoice.Late))
	default:
		return per.ErrEmpty
	}
	return nil
}

func (releaseChoice *ReleaseChoice) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	idx, err := per.DecodeConstrainedWholeNumber(r, enc, 0, 1)
	if err != nil {
		return err
	}
	switch idx {
	case 0:
		var v RRCReleaseIEs
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		releaseChoice.RRCRelease = &v
	case 1:
		var v bool
		b1, err := per.DecodeBoolean(r, enc)
		if err != nil {
			return err
		}
		v = b1
		releaseChoice.Late = &v
	default:
		return per.ErrOverflow
	}
	return nil
}
