apiVersion: apps/v1
kind: Deployment
metadata:
  name: ella-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ella-core
  template:
    metadata:
      labels:
        app: ella-core
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {"name": "core-n2", "interface": "n2"},
            {"name": "core-n3", "interface": "n3"},
            {"name": "core-n6", "interface": "n6"}
          ]
    spec:
      containers:
      - name: core
        image: localhost:5000/ella-core:latest
        imagePullPolicy: Always
        command: ["pebble"]
        args: ["run", "--hold", "--http", ":38813", "--verbose"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: sysfs-bpf
          mountPath: /sys/fs/bpf
        - name: data-volume
          mountPath: /core/data
        ports:
        - containerPort: 5002
        - containerPort: 38412
      - name: network-tools
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do sleep 3600; done
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: config-volume
        configMap:
          name: core-config
      - name: data-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: sysfs-bpf
        hostPath:
          path: /sys/fs/bpf
          type: Directory
