apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ueransim-n2
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "n2-br",
    "ipam": {
      "type": "static",
      "addresses": [
        {"address": "192.168.253.6/24"}
      ]
    },
    "capabilities": {"mac": true}
  }'
