apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "router-n6",
              "interface": "core"
            }
          ]
    spec:
      containers:
      - name: router
        image: ghcr.io/ellanetworks/ubuntu-router:0.1
        command: ["/bin/bash", "-c"]
        args:
          - >
            sysctl -w net.ipv4.ip_forward=1;
            iptables-legacy -t nat -A POSTROUTING -o eth0 -j MASQUERADE;
            trap : TERM INT;
            python3 /responder.py 34242 & wait
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
