// SPDX-FileCopyrightText: Ella Networks Inc.
// SPDX-License-Identifier: BUSL-1.1

// Code generated by pergen. DO NOT EDIT.

//go:build !ignore

package ngaptest

import "github.com/ellanetworks/core/internal/per"

func (gNBID *GNBID) MarshalPER(w *per.Writer, enc per.Encoding) error {
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 4294967295, HasUB: true}, int64(gNBID.Value)); err != nil {
		return err
	}
	return nil
}

func (gNBID *GNBID) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	n0, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 4294967295, HasUB: true})
	if err != nil {
		return err
	}
	gNBID.Value = int(n0)
	return nil
}

func (gNBIDChoice *GNBIDChoice) MarshalPER(w *per.Writer, enc per.Encoding) error {
	switch {
	case gNBIDChoice.GNBID != nil:
		if err := per.EncodeConstrainedWholeNumber(w, enc, 0, 1, 0); err != nil {
			return err
		}
		if err := (*gNBIDChoice.GNBID).MarshalPER(w, enc); err != nil {
			return err
		}
	case gNBIDChoice.Explicit != nil:
		if err := per.EncodeConstrainedWholeNumber(w, enc, 0, 1, 1); err != nil {
			return err
		}
		if err := (*gNBIDChoice.Explicit).MarshalPER(w, enc); err != nil {
			return err
		}
	default:
		return per.ErrEmpty
	}
	return nil
}

func (gNBIDChoice *GNBIDChoice) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	idx, err := per.DecodeConstrainedWholeNumber(r, enc, 0, 1)
	if err != nil {
		return err
	}
	switch idx {
	case 0:
		var v GNBID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		gNBIDChoice.GNBID = &v
	case 1:
		var v GNBID
		if err := (&v).UnmarshalPER(r, enc); err != nil {
			return err
		}
		gNBIDChoice.Explicit = &v
	default:
		return per.ErrOverflow
	}
	return nil
}

func (globalGNBID *GlobalGNBID) MarshalPER(w *per.Writer, enc per.Encoding) error {
	if err := globalGNBID.PLMN.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := globalGNBID.GNBID.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (globalGNBID *GlobalGNBID) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	if err := (&globalGNBID.PLMN).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&globalGNBID.GNBID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	return nil
}

func (nGSetupRequest *NGSetupRequest) MarshalPER(w *per.Writer, enc per.Encoding) error {
	w.WriteBit(nGSetupRequest.RANNodeName != nil)
	if err := nGSetupRequest.GlobalRANNodeID.MarshalPER(w, enc); err != nil {
		return err
	}
	if nGSetupRequest.RANNodeName != nil {
		if err := per.EncodeString(w, enc, []byte((*nGSetupRequest.RANNodeName))); err != nil {
			return err
		}
	}
	if err := nGSetupRequest.SupportedTAList.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := nGSetupRequest.DefaultPagingDRX.MarshalPER(w, enc); err != nil {
		return err
	}
	return nil
}

func (nGSetupRequest *NGSetupRequest) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	p_RANNodeName, err := r.ReadBit()
	if err != nil {
		return err
	}
	if err := (&nGSetupRequest.GlobalRANNodeID).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if p_RANNodeName {
		var v string
		sp, err := per.DecodeString(r, enc)
		if err != nil {
			return err
		}
		v = string(sp)
		nGSetupRequest.RANNodeName = &v
	}
	if err := (&nGSetupRequest.SupportedTAList).UnmarshalPER(r, enc); err != nil {
		return err
	}
	if err := (&nGSetupRequest.DefaultPagingDRX).UnmarshalPER(r, enc); err != nil {
		return err
	}
	return nil
}

func (pLMNIdentity *PLMNIdentity) MarshalPER(w *per.Writer, enc per.Encoding) error {
	if err := per.EncodeOctetString(w, enc, 3, 3, true, true, false, pLMNIdentity.Value); err != nil {
		return err
	}
	return nil
}

func (pLMNIdentity *PLMNIdentity) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	p, err := per.DecodeOctetString(r, enc, 3, 3, true, true, false)
	if err != nil {
		return err
	}
	pLMNIdentity.Value = p
	return nil
}

func (pagingDRX *PagingDRX) MarshalPER(w *per.Writer, enc per.Encoding) error {
	if err := per.EncodeInteger(w, enc, per.Bounds{LB: 0, HasLB: true, UB: 3, HasUB: true}, int64(pagingDRX.Value)); err != nil {
		return err
	}
	return nil
}

func (pagingDRX *PagingDRX) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	n0, err := per.DecodeInteger(r, enc, per.Bounds{LB: 0, HasLB: true, UB: 3, HasUB: true})
	if err != nil {
		return err
	}
	pagingDRX.Value = int(n0)
	return nil
}

func (supportedTAIItem *SupportedTAIItem) MarshalPER(w *per.Writer, enc per.Encoding) error {
	if err := supportedTAIItem.PLMN.MarshalPER(w, enc); err != nil {
		return err
	}
	if err := per.EncodeOctetString(w, enc, 3, 3, true, true, false, supportedTAIItem.TAC); err != nil {
		return err
	}
	return nil
}

func (supportedTAIItem *SupportedTAIItem) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	if err := (&supportedTAIItem.PLMN).UnmarshalPER(r, enc); err != nil {
		return err
	}
	p, err := per.DecodeOctetString(r, enc, 3, 3, true, true, false)
	if err != nil {
		return err
	}
	supportedTAIItem.TAC = p
	return nil
}

func (supportedTAList *SupportedTAList) MarshalPER(w *per.Writer, enc per.Encoding) error {
	off := 0
	if err := per.EncodeLength(w, enc, 1, 256, true, int64(len(supportedTAList.Items)), func(count int64) error {
		end := off + int(count)
		for i := off; i < end; i++ {
			if err := supportedTAList.Items[i].MarshalPER(w, enc); err != nil {
				return err
			}
		}
		off = end
		return nil
	}); err != nil {
		return err
	}
	return nil
}

func (supportedTAList *SupportedTAList) UnmarshalPER(r *per.Reader, enc per.Encoding) error {
	supportedTAList.Items = nil
	if err := per.DecodeLength(r, enc, 1, 256, true, func(count int64) error {
		start := len(supportedTAList.Items)
		supportedTAList.Items = append(supportedTAList.Items, make([]SupportedTAIItem, count)...)
		for i := int64(0); i < count; i++ {
			if err := (&supportedTAList.Items[start+int(i)]).UnmarshalPER(r, enc); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return err
	}
	return nil
}
