// SPDX-FileCopyrightText: Ella Networks Inc.
// SPDX-License-Identifier: BUSL-1.1

package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/types"
	"strconv"
	"strings"
)

// emitStruct emits MarshalPER and UnmarshalPER methods for a SEQUENCE or SET
// type. SET with AUTOMATIC tagging encodes in declaration order (§21), which
// is identical to SEQUENCE.
func (g *generator) emitStruct(name string, s *structType) error {
	recv := receiverName(name)
	fields := s.fields

	// Split into root and extension addition fields.
	var rootFields, extFields []fieldInfo

	for i := range fields {
		if fields[i].tag.Ext {
			extFields = append(extFields, fields[i])
		} else {
			rootFields = append(rootFields, fields[i])
		}
	}

	extensible := len(extFields) > 0 || s.extSeq

	// Determine which root fields are in the OPTIONAL/DEFAULT preamble bitmap.
	var optionalIdx []int

	for i, fi := range rootFields {
		if fi.isOptional || fi.hasDefault {
			optionalIdx = append(optionalIdx, i)
		}
	}

	g.emitHeader(name)
	g.emitMarshalExt(recv, name, rootFields, extFields, optionalIdx, extensible)
	g.emitUnmarshalExt(recv, name, rootFields, extFields, optionalIdx, extensible)

	return nil
}

// emitHeader writes the file-level preamble (build tag, package clause, imports).
func (g *generator) emitHeader(_ string) {
	// Header is written once per package; accumulate into the main buffer.
	if g.buf.Len() == 0 {
		g.buf.WriteString("// SPDX-FileCopyrightText: Ella Networks Inc.\n")
		g.buf.WriteString("// SPDX-License-Identifier: BUSL-1.1\n\n")
		g.buf.WriteString("// Code generated by pergen. DO NOT EDIT.\n\n")
		g.buf.WriteString("//go:build !ignore\n\n")
		g.buf.WriteString("package " + g.pkg.Name + "\n\n")
		g.buf.WriteString("import \"" + perImportPath + "\"\n\n")
	}
}

// emitMarshalExt writes the MarshalPER method with extension support.
func (g *generator) emitMarshalExt(recv, typeName string, rootFields, extFields []fieldInfo, optionalIdx []int, extensible bool) {
	r := &g.buf
	fmt.Fprintf(r, "func (%s *%s) MarshalPER(w *per.Writer, enc per.Encoding) error {\n", recv, typeName)

	// Extension bit (§19.1): 1 if any extension addition is present.
	if extensible {
		if len(extFields) > 0 {
			fmt.Fprintf(r, "\tw.WriteBit(%s)\n", extPresentExpr(recv, extFields))
		} else {
			fmt.Fprintf(r, "\tw.WriteBit(false)\n")
		}
	}

	// Root preamble: one presence bit per optional/default root field.
	for _, idx := range optionalIdx {
		fi := rootFields[idx]

		expr := recv + "." + fi.name
		if fi.isOptional {
			fmt.Fprintf(r, "\tw.WriteBit(%s != nil)\n", expr)
		} else if fi.hasDefault {
			fmt.Fprintf(r, "\tw.WriteBit(%s != %s)\n", expr, fi.tag.DefaultExpr)
		}
	}

	// Root fields in declaration order.
	for i := range rootFields {
		fi := rootFields[i]

		expr := recv + "." + fi.name
		if fi.isOptional {
			fmt.Fprintf(r, "\tif %s != nil {\n", expr)
			g.emitFieldMarshal(r, recv, fi, "(*"+expr+")", 1)
			fmt.Fprintf(r, "\t}\n")
		} else if fi.hasDefault {
			fmt.Fprintf(r, "\tif %s != %s {\n", expr, fi.tag.DefaultExpr)
			g.emitFieldMarshal(r, recv, fi, expr, 1)
			fmt.Fprintf(r, "\t}\n")
		} else {
			g.emitFieldMarshal(r, recv, fi, expr, 0)
		}
	}

	// Extension additions (§19.6-19.9).
	if extensible && len(extFields) > 0 {
		fmt.Fprintf(r, "\tif %s {\n", extPresentExpr(recv, extFields))
		// Normally-small length = number of extension additions, then bitmap.
		fmt.Fprintf(r, "\t\tif err := per.EncodeNormallySmallLength(w, enc, %d, func(_ int64) error {\n", len(extFields))

		for _, ef := range extFields {
			fmt.Fprintf(r, "\t\t\tw.WriteBit(%s.%s != nil)\n", recv, ef.name)
		}

		fmt.Fprintf(r, "\t\t\treturn nil\n")
		fmt.Fprintf(r, "\t\t}); err != nil {\n")
		fmt.Fprintf(r, "\t\t\treturn err\n")
		fmt.Fprintf(r, "\t\t}\n")
		// Each present extension addition as open type.
		for _, ef := range extFields {
			expr := recv + "." + ef.name
			fmt.Fprintf(r, "\t\tif %s != nil {\n", expr)

			if ef.kind == kindDelegate {
				fmt.Fprintf(r, "\t\t\tif err := per.EncodeOpenType(w, enc, %s); err != nil {\n", expr)
				fmt.Fprintf(r, "\t\t\t\treturn err\n")
				fmt.Fprintf(r, "\t\t\t}\n")
			} else {
				// Primitive: wrap in MarshalerFunc. The inner w/enc shadow the
				// outer ones, so emitFieldMarshal can use w/enc as usual.
				expr := recv + "." + ef.name
				valExpr := "(*" + expr + ")"

				fmt.Fprintf(r, "\t\t\tif err := per.EncodeOpenType(w, enc, per.MarshalerFunc(func(w *per.Writer, enc per.Encoding) error {\n")
				g.emitFieldMarshal(r, recv, ef, valExpr, 3)
				fmt.Fprintf(r, "\t\t\t\treturn nil\n")
				fmt.Fprintf(r, "\t\t\t})); err != nil {\n")
				fmt.Fprintf(r, "\t\t\t\treturn err\n")
				fmt.Fprintf(r, "\t\t\t}\n")
			}

			fmt.Fprintf(r, "\t\t}\n")
		}

		fmt.Fprintf(r, "\t}\n")
	}

	fmt.Fprintf(r, "\treturn nil\n}\n\n")
}

// joinOr joins conditions with " || ".
func joinOr(conds []string) string {
	return strings.Join(conds, " || ")
}

// extPresentExpr returns the Go expression for "any extension field present".
func extPresentExpr(recv string, extFields []fieldInfo) string {
	conds := make([]string, 0, len(extFields))
	for _, ef := range extFields {
		conds = append(conds, recv+"."+ef.name+" != nil")
	}

	return joinOr(conds)
}

// emitFieldMarshal writes the encoding for a single field.
// expr is the Go expression for the field value (possibly dereferenced for
// optional pointer fields). indent is the number of extra tab levels.
func (g *generator) emitFieldMarshal(r *bytes.Buffer, _ string, fi fieldInfo, expr string, indent int) {
	prefix := strings.Repeat("\t", indent+1)

	switch fi.kind {
	case kindBool:
		fmt.Fprintf(r, "%sper.EncodeBoolean(w, enc, %s)\n", prefix, expr)
	case kindConstrainedInt, kindUnconstrainedInt:
		fmt.Fprintf(r, "%sif err := per.EncodeInteger(w, enc, %s, int64(%s)); err != nil {\n", prefix, fi.boundsExpr, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindOctetString:
		fmt.Fprintf(r, "%sif err := per.EncodeOctetString(w, enc, %d, %d, %t, %t, %t, %s); err != nil {\n",
			prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindBitString:
		fmt.Fprintf(r, "%sif err := per.EncodeBitString(w, enc, %d, %d, %t, %t, %t, per.BoolsToBits(%s), len(%s)); err != nil {\n",
			prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt, expr, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindDelegate:
		if fi.delegateIsValue {
			fmt.Fprintf(r, "%sif err := %s.MarshalPER(w, enc); err != nil {\n", prefix, expr)
		} else {
			fmt.Fprintf(r, "%sif err := (&%s).MarshalPER(w, enc); err != nil {\n", prefix, expr)
		}

		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindString:
		fmt.Fprintf(r, "%sif err := per.EncodeString(w, enc, []byte(%s)); err != nil {\n", prefix, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindREAL:
		fmt.Fprintf(r, "%sif err := per.EncodeREAL(w, enc, %s); err != nil {\n", prefix, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindSequenceOf:
		g.emitSequenceOfMarshal(r, fi, expr, indent)
	default:
		fmt.Fprintf(r, "%s// unsupported field %s\n", prefix, fi.name)
	}
}

// emitSequenceOfMarshal writes a SEQUENCE OF encode: length determinant + loop.
func (g *generator) emitSequenceOfMarshal(r *bytes.Buffer, fi fieldInfo, expr string, indent int) {
	prefix := strings.Repeat("\t", indent+1)
	elemStr := g.goTypeString(fi.elemType)
	hasUB := fi.hasSizeUB
	ub := fi.sizeUB
	lb := fi.sizeLB
	hasLB := fi.hasSizeLB

	fmt.Fprintf(r, "%soff := 0\n", prefix)
	fmt.Fprintf(r, "%sif err := per.EncodeLength(w, enc, %d, %d, %t, int64(len(%s)), func(count int64) error {\n",
		prefix, lb, ub, hasUB, expr)
	fmt.Fprintf(r, "%s\tend := off + int(count)\n", prefix)
	fmt.Fprintf(r, "%s\tfor i := off; i < end; i++ {\n", prefix)

	if g.implementsMarshalPER(asNamed(fi.elemType)) {
		fmt.Fprintf(r, "%s\t\tif err := %s[i].MarshalPER(w, enc); err != nil {\n", prefix, expr)
	} else {
		fmt.Fprintf(r, "%s\t\tif err := (&%s[i]).MarshalPER(w, enc); err != nil {\n", prefix, expr)
	}

	fmt.Fprintf(r, "%s\t\t\treturn err\n", prefix)
	fmt.Fprintf(r, "%s\t\t}\n", prefix)
	fmt.Fprintf(r, "%s\t}\n", prefix)
	fmt.Fprintf(r, "%s\toff = end\n", prefix)
	fmt.Fprintf(r, "%s\treturn nil\n", prefix)
	fmt.Fprintf(r, "%s}); err != nil {\n", prefix)
	fmt.Fprintf(r, "%s\treturn err\n", prefix)
	fmt.Fprintf(r, "%s}\n", prefix)

	_ = elemStr
	_ = hasLB
}

// asNamed returns the named type if t is named, else nil.
func asNamed(t types.Type) *types.Named {
	n, _ := t.(*types.Named)
	return n
}

// emitUnmarshalExt writes the UnmarshalPER method with extension support.
func (g *generator) emitUnmarshalExt(recv, typeName string, rootFields, extFields []fieldInfo, optionalIdx []int, extensible bool) {
	r := &g.buf
	fmt.Fprintf(r, "func (%s *%s) UnmarshalPER(r *per.Reader, enc per.Encoding) error {\n", recv, typeName)

	// Extension bit (if extensible).
	if extensible {
		fmt.Fprintf(r, "\textBit, err := r.ReadBit()\n")
		fmt.Fprintf(r, "\tif err != nil {\n\t\treturn err\n\t}\n")
	}

	// Read root preamble bits.
	for _, idx := range optionalIdx {
		fi := rootFields[idx]
		fmt.Fprintf(r, "\tp_%s, err := r.ReadBit()\n", fi.name)
		fmt.Fprintf(r, "\tif err != nil {\n\t\treturn err\n\t}\n")
	}

	// Decode root fields in order.
	for i := range rootFields {
		fi := rootFields[i]

		expr := recv + "." + fi.name
		if fi.isOptional {
			fmt.Fprintf(r, "\tif p_%s {\n", fi.name)
			fmt.Fprintf(r, "\t\tvar v %s\n", fi.typeStr)
			g.emitFieldUnmarshal(r, "v", fi, 1)
			fmt.Fprintf(r, "\t\t%s = &v\n", expr)
			fmt.Fprintf(r, "\t}\n")
		} else if fi.hasDefault {
			fmt.Fprintf(r, "\tif p_%s {\n", fi.name)
			g.emitFieldUnmarshal(r, expr, fi, 1)
			fmt.Fprintf(r, "\t} else {\n")
			fmt.Fprintf(r, "\t\t%s = %s\n", expr, fi.tag.DefaultExpr)
			fmt.Fprintf(r, "\t}\n")
		} else {
			g.emitFieldUnmarshal(r, expr, fi, 0)
		}
	}

	// Extension additions (§19.6-19.9).
	if extensible {
		fmt.Fprintf(r, "\tif extBit {\n")
		// Read normally-small length = count of extension additions, then bitmap.
		fmt.Fprintf(r, "\t\tvar extBits []bool\n")
		fmt.Fprintf(r, "\t\tif err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {\n")
		fmt.Fprintf(r, "\t\t\textBits = make([]bool, count)\n")
		fmt.Fprintf(r, "\t\t\tfor i := int64(0); i < count; i++ {\n")
		fmt.Fprintf(r, "\t\t\t\tb, err := r.ReadBit()\n")
		fmt.Fprintf(r, "\t\t\t\tif err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
		fmt.Fprintf(r, "\t\t\t\textBits[i] = b\n")
		fmt.Fprintf(r, "\t\t\t}\n")
		fmt.Fprintf(r, "\t\t\treturn nil\n")
		fmt.Fprintf(r, "\t\t}); err != nil {\n\t\t\treturn err\n\t\t}\n")
		// Decode present extension additions as open types.
		if len(extFields) > 0 {
			fmt.Fprintf(r, "\t\tfor i, present := range extBits {\n")
		} else {
			fmt.Fprintf(r, "\t\tfor _, present := range extBits {\n")
		}

		fmt.Fprintf(r, "\t\t\tif !present {\n\t\t\t\tcontinue\n\t\t\t}\n")

		if len(extFields) > 0 {
			fmt.Fprintf(r, "\t\t\tswitch i {\n")

			for j, ef := range extFields {
				expr := recv + "." + ef.name

				fmt.Fprintf(r, "\t\t\tcase %d:\n", j)
				fmt.Fprintf(r, "\t\t\t\tvar v %s\n", ef.typeStr)

				if ef.kind == kindDelegate {
					fmt.Fprintf(r, "\t\t\t\tif err := per.DecodeOpenType(r, enc, &v); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
				} else {
					// Primitive: wrap in UnmarshalerFunc.
					fmt.Fprintf(r, "\t\t\t\tif err := per.DecodeOpenType(r, enc, per.UnmarshalerFunc(func(r *per.Reader, enc per.Encoding) error {\n")
					g.emitFieldUnmarshal(r, "v", ef, 4)
					fmt.Fprintf(r, "\t\t\t\t\treturn nil\n")
					fmt.Fprintf(r, "\t\t\t\t})); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
				}

				fmt.Fprintf(r, "\t\t\t\t%s = &v\n", expr)
			}

			fmt.Fprintf(r, "\t\t\tdefault:\n")
			fmt.Fprintf(r, "\t\t\t\tif err := per.SkipOpenType(r, enc); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
			fmt.Fprintf(r, "\t\t\t}\n")
		} else {
			fmt.Fprintf(r, "\t\t\tif err := per.SkipOpenType(r, enc); err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
		}

		fmt.Fprintf(r, "\t\t}\n")
		fmt.Fprintf(r, "\t}\n")
	}

	fmt.Fprintf(r, "\treturn nil\n}\n\n")
}

// emitFieldUnmarshal writes the decoding for a single field into target
// (a variable name or field expression).
func (g *generator) emitFieldUnmarshal(r *bytes.Buffer, target string, fi fieldInfo, indent int) {
	prefix := strings.Repeat("\t", indent+1)

	switch fi.kind {
	case kindBool:
		fmt.Fprintf(r, "%sb%d, err := per.DecodeBoolean(r, enc)\n", prefix, fi.fieldIdx)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = b%d\n", prefix, target, fi.fieldIdx)
	case kindConstrainedInt, kindUnconstrainedInt:
		fmt.Fprintf(r, "%sn%d, err := per.DecodeInteger(r, enc, %s)\n", prefix, fi.fieldIdx, fi.boundsExpr)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = %s(n%d)\n", prefix, target, fi.typeStr, fi.fieldIdx)
	case kindOctetString:
		fmt.Fprintf(r, "%sp, err := per.DecodeOctetString(r, enc, %d, %d, %t, %t, %t)\n",
			prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = p\n", prefix, target)
	case kindBitString:
		fmt.Fprintf(r, "%sbs, nbits, err := per.DecodeBitString(r, enc, %d, %d, %t, %t, %t)\n",
			prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s_ = nbits\n%s%s = per.BitsToBools(bs, nbits)\n", prefix, prefix, target)
	case kindDelegate:
		if fi.delegateIsValue {
			fmt.Fprintf(r, "%sif err := (&%s).UnmarshalPER(r, enc); err != nil {\n", prefix, target)
		} else {
			fmt.Fprintf(r, "%sif err := %s.UnmarshalPER(r, enc); err != nil {\n", prefix, target)
		}

		fmt.Fprintf(r, "%s\treturn err\n%s}\n", prefix, prefix)
	case kindString:
		fmt.Fprintf(r, "%ssp, err := per.DecodeString(r, enc)\n", prefix)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = string(sp)\n", prefix, target)
	case kindREAL:
		fmt.Fprintf(r, "%sf, err := per.DecodeREAL(r, enc)\n", prefix)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = f\n", prefix, target)
	case kindSequenceOf:
		g.emitSequenceOfUnmarshal(r, fi, target, indent)
	default:
		fmt.Fprintf(r, "%s// unsupported field %s\n", prefix, fi.name)
	}
}

// emitSequenceOfUnmarshal writes a SEQUENCE OF decode: length determinant + loop.
func (g *generator) emitSequenceOfUnmarshal(r *bytes.Buffer, fi fieldInfo, target string, indent int) {
	prefix := strings.Repeat("\t", indent+1)
	lb := fi.sizeLB
	ub := fi.sizeUB
	hasUB := fi.hasSizeUB

	fmt.Fprintf(r, "%s%s = nil\n", prefix, target)
	fmt.Fprintf(r, "%sif err := per.DecodeLength(r, enc, %d, %d, %t, func(count int64) error {\n",
		prefix, lb, ub, hasUB)
	fmt.Fprintf(r, "%s\tstart := len(%s)\n", prefix, target)
	fmt.Fprintf(r, "%s\t%s = append(%s, make(%s, count)...)\n", prefix, target, target, fi.typeStr)
	fmt.Fprintf(r, "%s\tfor i := int64(0); i < count; i++ {\n", prefix)
	fmt.Fprintf(r, "%s\t\tif err := (&%s[start+int(i)]).UnmarshalPER(r, enc); err != nil {\n", prefix, target)
	fmt.Fprintf(r, "%s\t\t\treturn err\n", prefix)
	fmt.Fprintf(r, "%s\t\t}\n", prefix)
	fmt.Fprintf(r, "%s\t}\n", prefix)
	fmt.Fprintf(r, "%s\treturn nil\n", prefix)
	fmt.Fprintf(r, "%s}); err != nil {\n", prefix)
	fmt.Fprintf(r, "%s\treturn err\n", prefix)
	fmt.Fprintf(r, "%s}\n", prefix)
}

// ---- Output -----------------------------------------------------------------

// formatOutput runs the accumulated source through go/format and returns it.
func (g *generator) formatOutput() ([]byte, error) {
	if g.buf.Len() == 0 {
		return nil, errors.New("no generated code")
	}

	src := g.buf.Bytes()
	// go/format requires a valid file; our header includes package + import.
	formatted, err := formatSource(src)
	if err != nil {
		return src, fmt.Errorf("format: %w", err)
	}

	return formatted, nil
}

// formatSource wraps go/format.Source with a fallback that returns the original
// on error (so the user can inspect the unformatted output for debugging).
func formatSource(src []byte) ([]byte, error) {
	return goFormat(src)
}

// write now actually writes the formatted output to the configured file.
func (g *generator) write() error {
	if g.pkg == nil {
		return errors.New("no package loaded")
	}

	if g.buf.Len() == 0 {
		return errors.New("nothing generated")
	}

	out, err := g.formatOutput()
	if err != nil {
		// Write unformatted for inspection.
		out = g.buf.Bytes()
	}

	return writeFile(g.cfg.dir, g.cfg.output, out)
}

// goFormat is a thin wrapper over go/format.Source.
var goFormat = func(src []byte) ([]byte, error) {
	return goFormatImpl(src)
}

// goFormatImpl is set in format.go to avoid importing go/format in emit.go.
var goFormatImpl func([]byte) ([]byte, error)

// writeFile is set in output.go.
var writeFile func(dir, filename string, data []byte) error

// strconv import used in some emitters.
var _ = strconv.Itoa
