// SPDX-FileCopyrightText: Ella Networks Inc.
// SPDX-License-Identifier: BUSL-1.1

package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// emitStruct emits the codec for a SEQUENCE or SET. A SET with AUTOMATIC
// tagging encodes in declaration order (X.691 §21), identical to a SEQUENCE.
func (g *generator) emitStruct(name string, s *structType) error {
	recv := receiverName(name)
	fields := s.fields

	var rootFields, extFields []fieldInfo

	for i := range fields {
		if fields[i].tag.Ext {
			extFields = append(extFields, fields[i])
		} else {
			rootFields = append(rootFields, fields[i])
		}
	}

	extensible := len(extFields) > 0 || s.extSeq

	// Root fields carrying a bit in the OPTIONAL/DEFAULT preamble bitmap.
	var optionalIdx []int

	for i, fi := range rootFields {
		if fi.isOptional || fi.hasDefault || fi.isSkip {
			optionalIdx = append(optionalIdx, i)
		}
	}

	g.emitHeader(name)
	g.emitMarshalExt(recv, name, rootFields, extFields, optionalIdx, extensible)
	g.emitUnmarshalExt(recv, name, rootFields, extFields, optionalIdx, extensible)

	return nil
}

// emitHeader writes the file preamble once per package.
func (g *generator) emitHeader(_ string) {
	if g.buf.Len() == 0 {
		g.buf.WriteString("// Code generated by pergen. DO NOT EDIT.\n\n")
		g.buf.WriteString("//go:build !ignore\n\n")
		g.buf.WriteString("package " + g.pkg.Name + "\n\n")
		g.buf.WriteString("import \"" + perImportPath + "\"\n\n")
	}
}

func (g *generator) emitMarshalExt(recv, typeName string, rootFields, extFields []fieldInfo, optionalIdx []int, extensible bool) {
	r := &g.buf
	fmt.Fprintf(r, "func (%s *%s) MarshalPER(w *per.Writer, enc per.Encoding) error {\n", recv, typeName)

	// Extension bit (X.691 §19.1): set when any extension addition is present.
	if extensible {
		if len(extFields) > 0 {
			fmt.Fprintf(r, "\tw.WriteBit(%s)\n", extPresentExpr(recv, extFields))
		} else {
			fmt.Fprintf(r, "\tw.WriteBit(false)\n")
		}
	}

	for _, idx := range optionalIdx {
		fi := rootFields[idx]

		expr := recv + "." + fi.name

		switch {
		case fi.isSkip:
			fmt.Fprintf(r, "\tw.WriteBit(false)\n")
		case fi.isOptional:
			fmt.Fprintf(r, "\tw.WriteBit(%s != nil)\n", expr)
		case fi.hasDefault:
			fmt.Fprintf(r, "\tw.WriteBit(%s != %s)\n", expr, fi.tag.DefaultExpr)
		}
	}

	for i := range rootFields {
		fi := rootFields[i]

		expr := recv + "." + fi.name
		if fi.isSkip {
			continue
		} else if fi.isOptional {
			valExpr := "(*" + expr + ")"
			if fi.noDeref {
				valExpr = expr
			}

			fmt.Fprintf(r, "\tif %s != nil {\n", expr)
			g.emitFieldMarshal(r, recv, fi, valExpr, 1)
			fmt.Fprintf(r, "\t}\n")
		} else if fi.hasDefault {
			fmt.Fprintf(r, "\tif %s != %s {\n", expr, fi.tag.DefaultExpr)
			g.emitFieldMarshal(r, recv, fi, expr, 1)
			fmt.Fprintf(r, "\t}\n")
		} else {
			g.emitFieldMarshal(r, recv, fi, expr, 0)
		}
	}

	// Extension additions (X.691 §19.6-19.9).
	if extensible && len(extFields) > 0 {
		fmt.Fprintf(r, "\tif %s {\n", extPresentExpr(recv, extFields))
		fmt.Fprintf(r, "\t\tif err := per.EncodeNormallySmallLength(w, enc, %d, func(_ int64) error {\n", len(extFields))

		for _, ef := range extFields {
			fmt.Fprintf(r, "\t\t\tw.WriteBit(%s.%s != nil)\n", recv, ef.name)
		}

		fmt.Fprintf(r, "\t\t\treturn nil\n")
		fmt.Fprintf(r, "\t\t}); err != nil {\n")
		fmt.Fprintf(r, "\t\t\treturn err\n")
		fmt.Fprintf(r, "\t\t}\n")

		for _, ef := range extFields {
			expr := recv + "." + ef.name
			fmt.Fprintf(r, "\t\tif %s != nil {\n", expr)

			if ef.kind == kindDelegate {
				fmt.Fprintf(r, "\t\t\tif err := per.EncodeOpenType(w, enc, %s); err != nil {\n", expr)
				fmt.Fprintf(r, "\t\t\t\treturn err\n")
				fmt.Fprintf(r, "\t\t\t}\n")
			} else {
				// The MarshalerFunc parameters deliberately shadow the outer
				// w/enc so emitFieldMarshal can name them unchanged.
				expr := recv + "." + ef.name
				valExpr := "(*" + expr + ")"

				fmt.Fprintf(r, "\t\t\tif err := per.EncodeOpenType(w, enc, per.MarshalerFunc(func(w *per.Writer, enc per.Encoding) error {\n")
				g.emitFieldMarshal(r, recv, ef, valExpr, 3)
				fmt.Fprintf(r, "\t\t\t\treturn nil\n")
				fmt.Fprintf(r, "\t\t\t})); err != nil {\n")
				fmt.Fprintf(r, "\t\t\t\treturn err\n")
				fmt.Fprintf(r, "\t\t\t}\n")
			}

			fmt.Fprintf(r, "\t\t}\n")
		}

		fmt.Fprintf(r, "\t}\n")
	}

	fmt.Fprintf(r, "\treturn nil\n}\n\n")
}

// preambleVar falls back to the field index for blank-named fields, since "_"
// is not a usable variable name.
func preambleVar(fi fieldInfo) string {
	if fi.name == "_" {
		return fmt.Sprintf("p_f%d", fi.fieldIdx)
	}

	return "p_" + fi.name
}

func joinOr(conds []string) string {
	return strings.Join(conds, " || ")
}

func extPresentExpr(recv string, extFields []fieldInfo) string {
	conds := make([]string, 0, len(extFields))
	for _, ef := range extFields {
		conds = append(conds, recv+"."+ef.name+" != nil")
	}

	return joinOr(conds)
}

// emitFieldMarshal encodes the field value named by expr, already dereferenced
// where it is an optional pointer. indent is the number of extra tab levels.
func (g *generator) emitFieldMarshal(r *bytes.Buffer, _ string, fi fieldInfo, expr string, indent int) {
	prefix := strings.Repeat("\t", indent+1)

	switch fi.kind {
	case kindBool:
		fmt.Fprintf(r, "%sper.EncodeBoolean(w, enc, %s)\n", prefix, expr)
	case kindConstrainedInt, kindUnconstrainedInt:
		fmt.Fprintf(r, "%sif err := per.EncodeInteger(w, enc, %s, int64(%s)); err != nil {\n", prefix, fi.boundsExpr, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindEnum:
		fmt.Fprintf(r, "%sif err := per.EncodeEnumerated(w, enc, %d, %t, int64(%s)); err != nil {\n", prefix, fi.enumRoot, fi.enumExt, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindOctetString:
		fmt.Fprintf(r, "%sif err := per.EncodeOctetString(w, enc, %d, %d, %t, %t, %t, %s); err != nil {\n",
			prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindBitString:
		fmt.Fprintf(r, "%sif err := per.EncodeBitString(w, enc, %d, %d, %t, %t, %t, per.BoolsToBits(%s), len(%s)); err != nil {\n",
			prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt, expr, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindDelegate:
		if fi.delegateIsValue {
			fmt.Fprintf(r, "%sif err := %s.MarshalPER(w, enc); err != nil {\n", prefix, expr)
		} else {
			fmt.Fprintf(r, "%sif err := (&%s).MarshalPER(w, enc); err != nil {\n", prefix, expr)
		}

		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindString:
		switch {
		case fi.charTypeExpr != "":
			fmt.Fprintf(r, "%sif err := per.EncodeKnownMultiplierString(w, enc, %s, %d, %d, %t, %t, %t, %s); err != nil {\n",
				prefix, fi.charTypeExpr, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt, expr)
		case fi.hasSizeLB || fi.hasSizeUB:
			// A size-constrained string with no known-multiplier type encodes 8
			// bits per character, sharing the OCTET STRING procedures.
			fmt.Fprintf(r, "%sif err := per.EncodeOctetString(w, enc, %d, %d, %t, %t, %t, []byte(%s)); err != nil {\n",
				prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt, expr)
		default:
			fmt.Fprintf(r, "%sif err := per.EncodeString(w, enc, []byte(%s)); err != nil {\n", prefix, expr)
		}

		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindREAL:
		fmt.Fprintf(r, "%sif err := per.EncodeREAL(w, enc, %s); err != nil {\n", prefix, expr)
		fmt.Fprintf(r, "%s\treturn err\n", prefix)
		fmt.Fprintf(r, "%s}\n", prefix)
	case kindSequenceOf:
		g.emitSequenceOfMarshal(r, fi, expr, indent)
	default:
		fmt.Fprintf(r, "%s// unsupported field %s\n", prefix, fi.name)
	}
}

func (g *generator) emitSequenceOfMarshal(r *bytes.Buffer, fi fieldInfo, expr string, indent int) {
	prefix := strings.Repeat("\t", indent+1)
	elemStr := g.goTypeString(fi.elemType)
	hasUB := fi.hasSizeUB
	ub := fi.sizeUB
	lb := fi.sizeLB
	hasLB := fi.hasSizeLB

	off := fmt.Sprintf("off%d", fi.fieldIdx)
	fmt.Fprintf(r, "%s%s := 0\n", prefix, off)
	fmt.Fprintf(r, "%sif err := per.EncodeLength(w, enc, %d, %d, %t, int64(len(%s)), func(count int64) error {\n",
		prefix, lb, ub, hasUB, expr)
	fmt.Fprintf(r, "%s\tend := %s + int(count)\n", prefix, off)
	fmt.Fprintf(r, "%s\tfor i := %s; i < end; i++ {\n", prefix, off)

	if g.implementsMarshalPER(asNamed(fi.elemType)) {
		fmt.Fprintf(r, "%s\t\tif err := %s[i].MarshalPER(w, enc); err != nil {\n", prefix, expr)
	} else {
		fmt.Fprintf(r, "%s\t\tif err := (&%s[i]).MarshalPER(w, enc); err != nil {\n", prefix, expr)
	}

	fmt.Fprintf(r, "%s\t\t\treturn err\n", prefix)
	fmt.Fprintf(r, "%s\t\t}\n", prefix)
	fmt.Fprintf(r, "%s\t}\n", prefix)
	fmt.Fprintf(r, "%s\t%s = end\n", prefix, off)
	fmt.Fprintf(r, "%s\treturn nil\n", prefix)
	fmt.Fprintf(r, "%s}); err != nil {\n", prefix)
	fmt.Fprintf(r, "%s\treturn err\n", prefix)
	fmt.Fprintf(r, "%s}\n", prefix)

	_ = elemStr
	_ = hasLB
}

func asNamed(t types.Type) *types.Named {
	n, _ := t.(*types.Named)
	return n
}

func (g *generator) emitUnmarshalExt(recv, typeName string, rootFields, extFields []fieldInfo, optionalIdx []int, extensible bool) {
	r := &g.buf
	fmt.Fprintf(r, "func (%s *%s) UnmarshalPER(r *per.Reader, enc per.Encoding) error {\n", recv, typeName)

	if extensible {
		fmt.Fprintf(r, "\textBit, err := r.ReadBit()\n")
		fmt.Fprintf(r, "\tif err != nil {\n\t\treturn err\n\t}\n")
	}

	for _, idx := range optionalIdx {
		fi := rootFields[idx]
		fmt.Fprintf(r, "\t%s, err := r.ReadBit()\n", preambleVar(fi))
		fmt.Fprintf(r, "\tif err != nil {\n\t\treturn err\n\t}\n")
	}

	for i := range rootFields {
		fi := rootFields[i]

		expr := recv + "." + fi.name
		if fi.isSkip {
			fmt.Fprintf(r, "\tif %s {\n", preambleVar(fi))
			fmt.Fprintf(r, "\t\tvar v %s\n", fi.typeStr)
			g.emitFieldUnmarshal(r, "v", fi, 1)
			fmt.Fprintf(r, "\t\t_ = v\n")
			fmt.Fprintf(r, "\t}\n")
		} else if fi.isOptional {
			fmt.Fprintf(r, "\tif %s {\n", preambleVar(fi))

			if fi.noDeref {
				g.emitFieldUnmarshal(r, expr, fi, 1)
			} else {
				fmt.Fprintf(r, "\t\tvar v %s\n", fi.typeStr)
				g.emitFieldUnmarshal(r, "v", fi, 1)
				fmt.Fprintf(r, "\t\t%s = &v\n", expr)
			}

			fmt.Fprintf(r, "\t}\n")
		} else if fi.hasDefault {
			fmt.Fprintf(r, "\tif %s {\n", preambleVar(fi))
			g.emitFieldUnmarshal(r, expr, fi, 1)
			fmt.Fprintf(r, "\t} else {\n")
			fmt.Fprintf(r, "\t\t%s = %s\n", expr, fi.tag.DefaultExpr)
			fmt.Fprintf(r, "\t}\n")
		} else {
			g.emitFieldUnmarshal(r, expr, fi, 0)
		}
	}

	// Extension additions (X.691 §19.6-19.9).
	if extensible {
		fmt.Fprintf(r, "\tif extBit {\n")
		fmt.Fprintf(r, "\t\tvar extBits []bool\n")
		fmt.Fprintf(r, "\t\tif err := per.DecodeNormallySmallLength(r, enc, func(count int64) error {\n")
		fmt.Fprintf(r, "\t\t\textBits = make([]bool, count)\n")
		fmt.Fprintf(r, "\t\t\tfor i := int64(0); i < count; i++ {\n")
		fmt.Fprintf(r, "\t\t\t\tb, err := r.ReadBit()\n")
		fmt.Fprintf(r, "\t\t\t\tif err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
		fmt.Fprintf(r, "\t\t\t\textBits[i] = b\n")
		fmt.Fprintf(r, "\t\t\t}\n")
		fmt.Fprintf(r, "\t\t\treturn nil\n")
		fmt.Fprintf(r, "\t\t}); err != nil {\n\t\t\treturn err\n\t\t}\n")

		if len(extFields) > 0 {
			fmt.Fprintf(r, "\t\tfor i, present := range extBits {\n")
		} else {
			fmt.Fprintf(r, "\t\tfor _, present := range extBits {\n")
		}

		fmt.Fprintf(r, "\t\t\tif !present {\n\t\t\t\tcontinue\n\t\t\t}\n")

		if len(extFields) > 0 {
			fmt.Fprintf(r, "\t\t\tswitch i {\n")

			for j, ef := range extFields {
				expr := recv + "." + ef.name

				fmt.Fprintf(r, "\t\t\tcase %d:\n", j)
				fmt.Fprintf(r, "\t\t\t\tvar v %s\n", ef.typeStr)

				if ef.kind == kindDelegate {
					fmt.Fprintf(r, "\t\t\t\tif err := per.DecodeOpenType(r, enc, &v); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
				} else {
					fmt.Fprintf(r, "\t\t\t\tif err := per.DecodeOpenType(r, enc, per.UnmarshalerFunc(func(r *per.Reader, enc per.Encoding) error {\n")
					g.emitFieldUnmarshal(r, "v", ef, 4)
					fmt.Fprintf(r, "\t\t\t\t\treturn nil\n")
					fmt.Fprintf(r, "\t\t\t\t})); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
				}

				fmt.Fprintf(r, "\t\t\t\t%s = &v\n", expr)
			}

			fmt.Fprintf(r, "\t\t\tdefault:\n")
			fmt.Fprintf(r, "\t\t\t\tif err := per.SkipOpenType(r, enc); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
			fmt.Fprintf(r, "\t\t\t}\n")
		} else {
			fmt.Fprintf(r, "\t\t\tif err := per.SkipOpenType(r, enc); err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
		}

		fmt.Fprintf(r, "\t\t}\n")
		fmt.Fprintf(r, "\t}\n")
	}

	fmt.Fprintf(r, "\treturn nil\n}\n\n")
}

// emitFieldUnmarshal decodes into target, a variable name or field expression.
func (g *generator) emitFieldUnmarshal(r *bytes.Buffer, target string, fi fieldInfo, indent int) {
	prefix := strings.Repeat("\t", indent+1)

	switch fi.kind {
	case kindBool:
		fmt.Fprintf(r, "%sb%d, err := per.DecodeBoolean(r, enc)\n", prefix, fi.fieldIdx)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = b%d\n", prefix, target, fi.fieldIdx)
	case kindConstrainedInt, kindUnconstrainedInt:
		fmt.Fprintf(r, "%sn%d, err := per.DecodeInteger(r, enc, %s)\n", prefix, fi.fieldIdx, fi.boundsExpr)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = %s(n%d)\n", prefix, target, fi.typeStr, fi.fieldIdx)
	case kindEnum:
		// An extensible ENUMERATED goes through decodeRootEnumerated, which
		// refuses an extension addition rather than let nRoot+k narrow back
		// onto a root value in the enumeration's small Go type.
		if fi.enumExt {
			fmt.Fprintf(r, "%se%d, err := decodeRootEnumerated(r, enc, %d, %q)\n", prefix, fi.fieldIdx, fi.enumRoot, fi.typeStr)
		} else {
			fmt.Fprintf(r, "%se%d, err := per.DecodeEnumerated(r, enc, %d, false)\n", prefix, fi.fieldIdx, fi.enumRoot)
		}

		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = %s(e%d)\n", prefix, target, fi.typeStr, fi.fieldIdx)
	case kindOctetString:
		fmt.Fprintf(r, "%sp, err := per.DecodeOctetString(r, enc, %d, %d, %t, %t, %t)\n",
			prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = p\n", prefix, target)
	case kindBitString:
		fmt.Fprintf(r, "%sbs, nbits, err := per.DecodeBitString(r, enc, %d, %d, %t, %t, %t)\n",
			prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s_ = nbits\n%s%s = per.BitsToBools(bs, nbits)\n", prefix, prefix, target)
	case kindDelegate:
		if fi.delegateIsValue {
			fmt.Fprintf(r, "%sif err := (&%s).UnmarshalPER(r, enc); err != nil {\n", prefix, target)
		} else {
			fmt.Fprintf(r, "%sif err := %s.UnmarshalPER(r, enc); err != nil {\n", prefix, target)
		}

		fmt.Fprintf(r, "%s\treturn err\n%s}\n", prefix, prefix)
	case kindString:
		switch {
		case fi.charTypeExpr != "":
			fmt.Fprintf(r, "%ssp, err := per.DecodeKnownMultiplierString(r, enc, %s, %d, %d, %t, %t, %t)\n",
				prefix, fi.charTypeExpr, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt)
			fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
			fmt.Fprintf(r, "%s%s = sp\n", prefix, target)

			return
		case fi.hasSizeLB || fi.hasSizeUB:
			fmt.Fprintf(r, "%ssp, err := per.DecodeOctetString(r, enc, %d, %d, %t, %t, %t)\n",
				prefix, fi.sizeLB, fi.sizeUB, fi.hasSizeLB, fi.hasSizeUB, fi.sizeExt)
		default:
			fmt.Fprintf(r, "%ssp, err := per.DecodeString(r, enc)\n", prefix)
		}

		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = string(sp)\n", prefix, target)
	case kindREAL:
		fmt.Fprintf(r, "%sf, err := per.DecodeREAL(r, enc)\n", prefix)
		fmt.Fprintf(r, "%sif err != nil {\n%s\treturn err\n%s}\n", prefix, prefix, prefix)
		fmt.Fprintf(r, "%s%s = f\n", prefix, target)
	case kindSequenceOf:
		g.emitSequenceOfUnmarshal(r, fi, target, indent)
	default:
		fmt.Fprintf(r, "%s// unsupported field %s\n", prefix, fi.name)
	}
}

func (g *generator) emitSequenceOfUnmarshal(r *bytes.Buffer, fi fieldInfo, target string, indent int) {
	prefix := strings.Repeat("\t", indent+1)
	lb := fi.sizeLB
	ub := fi.sizeUB
	hasUB := fi.hasSizeUB

	fmt.Fprintf(r, "%s%s = nil\n", prefix, target)
	fmt.Fprintf(r, "%sif err := per.DecodeLength(r, enc, %d, %d, %t, func(count int64) error {\n",
		prefix, lb, ub, hasUB)
	fmt.Fprintf(r, "%s\tstart := len(%s)\n", prefix, target)
	fmt.Fprintf(r, "%s\t%s = append(%s, make(%s, count)...)\n", prefix, target, target, fi.typeStr)
	fmt.Fprintf(r, "%s\tfor i := int64(0); i < count; i++ {\n", prefix)
	fmt.Fprintf(r, "%s\t\tif err := (&%s[start+int(i)]).UnmarshalPER(r, enc); err != nil {\n", prefix, target)
	fmt.Fprintf(r, "%s\t\t\treturn err\n", prefix)
	fmt.Fprintf(r, "%s\t\t}\n", prefix)
	fmt.Fprintf(r, "%s\t}\n", prefix)
	fmt.Fprintf(r, "%s\treturn nil\n", prefix)
	fmt.Fprintf(r, "%s}); err != nil {\n", prefix)
	fmt.Fprintf(r, "%s\treturn err\n", prefix)
	fmt.Fprintf(r, "%s}\n", prefix)
}

func (g *generator) formatOutput() ([]byte, error) {
	if g.buf.Len() == 0 {
		return nil, errors.New("no generated code")
	}

	formatted, err := format.Source(g.buf.Bytes())
	if err != nil {
		return g.buf.Bytes(), fmt.Errorf("format: %w", err)
	}

	return formatted, nil
}

func (g *generator) write() error {
	if g.pkg == nil {
		return errors.New("no package loaded")
	}

	if g.buf.Len() == 0 {
		return errors.New("nothing generated")
	}

	out, err := g.formatOutput()
	if err != nil {
		// Unformatted output is still written, so a syntax defect can be read.
		out = g.buf.Bytes()
	}

	wd, err := os.Getwd()
	if err != nil {
		return err
	}

	absPath, err := filepath.Abs(g.cfg.output)
	if err != nil {
		return err
	}

	rel, err := filepath.Rel(wd, absPath)
	if err != nil {
		return err
	}

	if strings.HasPrefix(rel, "..") {
		return fmt.Errorf("output path escapes working directory: %s", g.cfg.output)
	}

	// #nosec G703: the output path is validated above to sit under the
	// working directory, so this cannot traverse outside it.
	return os.WriteFile(absPath, out, 0o600)
}

var _ = strconv.Itoa
