/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pdusession

import (
	"errors"
	"log"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi"
	"github.com/omec-project/openapi/models"
	"github.com/omec-project/util/httpwrapper"
	"github.com/yeastengine/ella/internal/smf/fsm"
	"github.com/yeastengine/ella/internal/smf/logger"
	"github.com/yeastengine/ella/internal/smf/msgtypes/svcmsgtypes"
	"github.com/yeastengine/ella/internal/smf/transaction"
)

// HTTPReleaseSmContext - Release SM Context
func HTTPReleaseSmContext(c *gin.Context) {
	logger.PduSessLog.Info("Receive Release SM Context Request")

	var request models.ReleaseSmContextRequest
	request.JsonData = new(models.SmContextReleaseData)

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}
	if err != nil {
		log.Print(err)
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, request)
	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	smContextRef := req.Params["smContextRef"]
	txn := transaction.NewTransaction(req.Body.(models.ReleaseSmContextRequest), nil, svcmsgtypes.SmfMsgType(svcmsgtypes.ReleaseSmContext))
	txn.CtxtKey = smContextRef
	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status

	// producer.HandlePDUSessionSMContextRelease(
	//	smContextRef, req.Body.(models.ReleaseSmContextRequest))

	c.Status(http.StatusNoContent)
}

func ReleaseSmContext(smContextRef string, releaseSmContextRequest models.ReleaseSmContextRequest) error {
	logger.PduSessLog.Info("Processing Release SM Context Request")

	// Validate the request content
	if releaseSmContextRequest.JsonData == nil {
		return errors.New("release request is missing JsonData")
	}

	// Start transaction
	txn := transaction.NewTransaction(releaseSmContextRequest, nil, svcmsgtypes.SmfMsgType(svcmsgtypes.ReleaseSmContext))
	txn.CtxtKey = smContextRef

	// Execute FSM lifecycle
	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status // Wait for transaction to complete

	// Handle transaction response
	HTTPResponse, ok := txn.Rsp.(*httpwrapper.Response)
	if !ok {
		return errors.New("unexpected transaction response type")
	}

	// Process response based on HTTP status
	switch HTTPResponse.Status {
	case http.StatusNoContent:
		// Successful release
		return nil
	default:
		// Handle errors
		errResponse, ok := HTTPResponse.Body.(*models.ProblemDetails)
		if ok {
			logger.PduSessLog.Errorf("SM Context release failed: %s", errResponse.Detail)
			return errors.New(errResponse.Detail)
		}
		return errors.New("unexpected error during SM Context release")
	}
}

// RetrieveSmContext - Retrieve SM Context
func RetrieveSmContext(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HTTPUpdateSmContext - Update SM Context
func HTTPUpdateSmContext(c *gin.Context) {
	logger.PduSessLog.Info("Receive Update SM Context Request")

	var request models.UpdateSmContextRequest
	request.JsonData = new(models.SmContextUpdateData)

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.PduSessLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)

		log.Print(err)
		return
	}

	req := httpwrapper.NewRequest(c.Request, request)
	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	smContextRef := req.Params["smContextRef"]

	txn := transaction.NewTransaction(req.Body.(models.UpdateSmContextRequest), nil, svcmsgtypes.SmfMsgType(svcmsgtypes.UpdateSmContext))
	txn.CtxtKey = smContextRef
	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status
	HTTPResponse := txn.Rsp.(*httpwrapper.Response)
	// HTTPResponse := producer.HandlePDUSessionSMContextUpdate(
	//	smContextRef, req.Body.(models.UpdateSmContextRequest))

	if HTTPResponse.Status < 300 {
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	} else {
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}
}

func UpdateSmContext(smContextRef string, updateSmContextRequest models.UpdateSmContextRequest) (*models.UpdateSmContextResponse, error) {
	logger.PduSessLog.Info("Processing Update SM Context Request")

	// Validate the request content
	if updateSmContextRequest.JsonData == nil {
		return nil, errors.New("update request is missing JsonData")
	}

	// Start transaction
	txn := transaction.NewTransaction(updateSmContextRequest, nil, svcmsgtypes.SmfMsgType(svcmsgtypes.UpdateSmContext))
	txn.CtxtKey = smContextRef

	// Execute FSM lifecycle
	go txn.StartTxnLifeCycle(fsm.SmfTxnFsmHandle)
	<-txn.Status // Wait for transaction to complete

	// Handle transaction response
	HTTPResponse, ok := txn.Rsp.(*httpwrapper.Response)
	if !ok {
		return nil, errors.New("unexpected transaction response type")
	}

	// Process response based on HTTP status
	switch HTTPResponse.Status {
	case http.StatusOK, http.StatusNoContent:
		// Successful update
		response, ok := HTTPResponse.Body.(models.UpdateSmContextResponse)
		if !ok {
			return nil, errors.New("unexpected response body type for successful update")
		}
		return &response, nil

	default:
		// Handle errors
		errResponse, ok := HTTPResponse.Body.(*models.ProblemDetails)
		if ok {
			logger.PduSessLog.Errorf("SM Context update failed: %s", errResponse.Detail)
			return nil, errors.New(errResponse.Detail)
		}
		return nil, errors.New("unexpected error during SM Context update")
	}
}
