name: ella-core
base: core22
adopt-info: core-release-data
summary: Ella Core is a secure, reliable, and easy to operate mobile network.
description: |
  Ella Core is a secure, reliable, and easy to operate mobile network.

grade: devel
confinement: devmode

apps:
  cored:
    daemon: simple
    install-mode: disable
    command: bin/core-start
    refresh-mode: endure
    restart-condition: on-failure

parts:
  core:
    plugin: go
    source: .
    source-type: local
    build-snaps:
      - go/1.23/stable
      - node/20/stable
    override-build: |
      npm install --prefix ui
      npm run build --prefix ui
      craftctl default

  service-files:
    plugin: dump
    source: service

  core-release-data:
    plugin: nil
    source: .
    override-build: |
      version="$(cat version/VERSION)"
      craftctl set version="$version"