name: moose
base: core22
version: '0.0.0'
summary: The simplest way to operate a 5G core network
description: |
  The simplest way to operate a 5G core network

grade: devel
confinement: devmode

package-repositories:
  - type: apt
    components: [multiverse]
    suites: [jammy/mongodb-org/7.0]
    key-id: E58830201F7DD82CD808AA84160D26BB1785BA38
    url: https://repo.mongodb.org/apt/ubuntu

parts:
  moose:
    plugin: go
    source: .
    build-snaps:
      - go/1.22/stable
  
  mongodb:
    plugin: nil
    stage-packages:
      - mongodb-org
    stage:
      - usr/bin
      - usr/lib

  config:
    plugin: dump
    source: .
    organize:
      config.yaml: etc/config.yaml
    stage:
      - etc/config.yaml
