name: ella-core
title: Ella Core
base: core24
adopt-info: core-release-data
summary: Ella Core is a 5G mobile core network designed for private deployments.
description: |
  Ella Core is a 5G mobile core network designed for private deployments. It consolidates the complexity of traditional 5G networks into a single application, offering simplicity, reliability, and security.

  Typical mobile networks are expensive, complex, and inadequate for private deployments. They require a team of experts to deploy, maintain, and operate. Open source alternatives are often incomplete, difficult to use, and geared towards research and development. Ella Core is an open-source, production-geared solution that simplifies the deployment and operation of private mobile networks.

  Use Ella Core where you need 5G connectivity: in a factory, a warehouse, a farm, a stadium, a ship, a military base, or a remote location.

source-code: https://github.com/ellanetworks/core
issues:
  - https://github.com/ellanetworks/core/issues
website:
  - https://docs.ellanetworks.com
grade: stable
confinement: strict
license: Apache-2.0
icon: docs/images/logo.png

apps:
  cored:
    daemon: simple
    install-mode: disable
    command: bin/core-start
    refresh-mode: endure
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - network-control
      - process-control
      - system-observe
      - firewall-control

parts:
  core:
    plugin: go
    source: .
    source-type: local
    build-packages:
      - git
    build-snaps:
      - go/1.25/stable
      - node/24/stable
    override-build: |
      npm install --prefix ui
      npm run build --prefix ui
      REVISION=`git rev-parse HEAD`
      go build -v -o ${CRAFT_PART_INSTALL}/bin/core -ldflags "-X github.com/ellanetworks/core/version.GitCommit=${REVISION}" ./cmd/core

  service-files:
    plugin: dump
    source: service

  core-release-data:
    plugin: nil
    source: .
    override-build: |
      version="$(cat version/VERSION)"
      craftctl set version="$version"
