name: canard
base: core22
version: '0.0.0'
summary: Canard is a secure, reliable, and easy to operate mobile network.
description: |
  Canard is a secure, reliable, and easy to operate mobile network.

grade: devel
confinement: devmode

package-repositories:
  - type: apt
    components: [multiverse]
    suites: [jammy/mongodb-org/7.0]
    key-id: E58830201F7DD82CD808AA84160D26BB1785BA38
    url: https://repo.mongodb.org/apt/ubuntu

apps:
  canard:
    daemon: simple
    install-mode: disable
    command: bin/canard --config /etc/canard.yaml
    refresh-mode: endure
    restart-condition: on-failure

parts:
  canard:
    plugin: go
    source: .
    build-snaps:
      - go/1.22/stable
  
  mongodb:
    plugin: nil
    stage-packages:
      - mongodb-org
    stage:
      - usr/bin
      - usr/lib

  config:
    plugin: dump
    source: .
    organize:
      canard.yaml: etc/canard.yaml
    stage:
      - etc/canard.yaml
