name: canard
base: core22
version: '0.0.0'
summary: Canard is a secure, reliable, and easy to operate mobile network.
description: |
  Canard is a secure, reliable, and easy to operate mobile network.

grade: devel
confinement: devmode

package-repositories:
  - type: apt
    components: [multiverse]
    suites: [jammy/mongodb-org/7.0]
    key-id: E58830201F7DD82CD808AA84160D26BB1785BA38
    url: https://repo.mongodb.org/apt/ubuntu

apps:
  canard:
    daemon: simple
    install-mode: disable
    command: bin/canard-start
    refresh-mode: endure
    restart-condition: on-failure

  ui:
    command: npm run start
    daemon: simple
    refresh-mode: endure
    restart-condition: on-failure
    environment:
      UPF_CONFIG_PATH: /etc/upf/upf.json
      GNB_CONFIG_PATH: /etc/gnb/gnb.json
      WEBUI_ENDPOINT: http://127.0.0.1:5000

parts:
  canard:
    plugin: go
    source: .
    build-snaps:
      - go/1.22/stable
  
  mongodb:
    plugin: nil
    stage-packages:
      - mongodb-org
    stage:
      - usr/bin
      - usr/lib
  
  frontend:
    plugin: nil
    source: ./ui
    stage-snaps:
      - node/20/stable
    build-snaps:
      - node/20/stable
    override-build: |
      mkdir -p ${CRAFT_PART_INSTALL}/ui
      
      npm ci
      npm run build

      cp -r .next ${CRAFT_PART_INSTALL}/ui/
      cp -r node_modules ${CRAFT_PART_INSTALL}/ui/
      cp package.json ${CRAFT_PART_INSTALL}/ui/
      cp -r pages ${CRAFT_PART_INSTALL}/ui/

  service-files:
    plugin: dump
    source: service
