name: ella
base: core22
version: '0.0.0'
summary: ella is a secure, reliable, and easy to operate mobile network.
description: |
  ella is a secure, reliable, and easy to operate mobile network.

grade: devel
confinement: devmode

package-repositories:
  - type: apt
    components: [multiverse]
    suites: [jammy/mongodb-org/7.0]
    key-id: E58830201F7DD82CD808AA84160D26BB1785BA38
    url: https://repo.mongodb.org/apt/ubuntu

apps:
  ella:
    daemon: simple
    install-mode: disable
    command: bin/ella-start
    refresh-mode: endure
    restart-condition: on-failure

parts:
  frontend:
    plugin: nil
    source: ./ui
    build-snaps:
      - node/20/stable
    stage-snaps:
      - node/20/stable
    override-build: |
      craftctl default
      npm ci
      npm run build

      mkdir -p ${CRAFT_PART_INSTALL}/app
      cp -r out/* ${CRAFT_PART_INSTALL}/app/

  ella:
    plugin: go
    after:
      - frontend
    go-buildtags:
      - ui
    source: .
    build-snaps:
      - go/1.22/stable
    override-build: |
      rm -rf ${CRAFT_PART_BUILD}/ui/frontend_files/*
      cp -r ${CRAFT_STAGE}/app/* ${CRAFT_PART_BUILD}/ui/frontend_files
      craftctl default
  
  mongodb:
    plugin: nil
    stage-packages:
      - mongodb-org
    stage:
      - usr/bin
      - usr/lib
  
  service-files:
    plugin: dump
    source: service
