configs:
  ella_config:
    content: |
      logging:
        system:
          level: "info"
          output: "stdout"
        audit:
          output: "stdout"
      db:
        path: "core.db"
      interfaces:
        n2:
          name: "n3"
        n3:
          name: "n3"
        n6:
          name: "n6"
        api:
          address: "0.0.0.0"
          port: 5002
      datapath:
        attach-mode: "xdp-generic"

services:
  ella-core:
    image: ${ELLA_CORE_IMAGE:-ella-core:latest}
    configs:
      - source: ella_config
        target: /core.yaml
    entrypoint: /bin/core --config /core.yaml
    privileged: true
    ports:
      - "${ELLA_E2E_PORT:-5102}:5002"
    networks:
      default:
      n3:
        driver_opts:
          com.docker.network.endpoint.ifname: n3
      n6:
        driver_opts:
          com.docker.network.endpoint.ifname: n6

networks:
  n3:
    internal: true
  n6:
