name: Rock Build

permissions:
  contents: read

on:
  workflow_call:

jobs:
  build-rock:
    strategy:
      matrix:
        arch:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: canonical/craft-actions/rockcraft-pack@91513c1bae43bc871c85ea2fdf2ac7eed91034f9 # main
        id: rockcraft
        with:
          rockcraft-channel: edge

      - name: Upload container image to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rock-${{ matrix.arch.arch }}
          path: ${{ steps.rockcraft.outputs.rock }}
