name: Rock Publish

permissions:
  contents: read
  packages: write

on:
  workflow_call:

jobs:
  publish-rock:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install rockcraft
        run: |
          sudo snap install rockcraft --classic --channel edge
      
      - uses: actions/download-artifact@v4
        with:
          name: rock-amd64
  
      - uses: actions/download-artifact@v4
        with:
          name: rock-arm64

      - name: Import and push to github package
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(cat version/VERSION)"
          amd64_rock_file=$(ls *_amd64.rock | tail -n 1)
          arm64_rock_file=$(ls *_arm64.rock | tail -n 1)
          sudo rockcraft.skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${amd64_rock_file}" \
            docker-daemon:"ghcr.io/ellanetworks/${image_name}:${version}-amd64"
          docker push ghcr.io/ellanetworks/${image_name}:${version}-amd64
          sudo rockcraft.skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${arm64_rock_file}" \
            docker-daemon:"ghcr.io/ellanetworks/${image_name}:${version}-arm64"
          docker push ghcr.io/ellanetworks/${image_name}:${version}-arm64
          docker manifest create ghcr.io/ellanetworks/${image_name}:${version} \
            ghcr.io/ellanetworks/${image_name}:${version}-amd64 \
            ghcr.io/ellanetworks/${image_name}:${version}-arm64
          docker manifest push ghcr.io/ellanetworks/${image_name}:${version}
          docker manifest create ghcr.io/ellanetworks/${image_name}:latest \
            ghcr.io/ellanetworks/${image_name}:${version}-amd64 \
            ghcr.io/ellanetworks/${image_name}:${version}-arm64
          docker manifest push ghcr.io/ellanetworks/${image_name}:latest