name: Rock Scan

permissions:
  contents: read
  security-events: write

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install rockcraft
        run: |
          sudo snap install rockcraft --classic --channel edge

      - name: Install yq
        run: |
          sudo snap install yq

      - uses: actions/download-artifact@v5
        with:
          name: rock

      - name: Import
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          echo "image_name=${image_name}" >> $GITHUB_ENV
          version="$(cat version/VERSION)"
          echo "version=${version}" >> $GITHUB_ENV
          rock_file=$(ls *.rock | tail -n 1)
          sudo rockcraft.skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/ellanetworks/${image_name}:${version}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@f9424c10c36e288d5fa79bd3dfd1aeb2d6eae808 # 0.33.0
        with:
          image-ref: "ghcr.io/ellanetworks/${{env.image_name}}:${{env.version}}"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
