name: Rock Publish

permissions:
  contents: read
  packages: write

on:
  workflow_call:

jobs:
  publish-rock:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install rockcraft
        run: |
          sudo snap install rockcraft --classic --channel edge
        
      - uses: actions/download-artifact@v4
        with:
          name: rock

      - name: Import and push to github package
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(cat version/VERSION)"
          rock_file=$(ls *.rock | tail -n 1)
          sudo rockcraft.skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/ellanetworks/${image_name}:${version}"
          docker tag ghcr.io/ellanetworks/${image_name}:${version} ghcr.io/ellanetworks/${image_name}:latest
          docker push ghcr.io/ellanetworks/${image_name}:${version}
          docker push ghcr.io/ellanetworks/${image_name}:latest
