name: Snap Build

permissions:
  contents: read

on:
  workflow_call:

jobs:
  build-snap:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Build snap
        uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 #v1.3.0
        id: build

      - name: Upload locally built snap artifact
        uses: actions/upload-artifact@v5
        with:
          name: snap
          path: ${{ steps.build.outputs.snap }}
