name: Snap Build

on:
  workflow_call:

jobs:
  build-snap:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: build
      
      - name: Upload locally built snap artifact
        if: ${{ github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.build.outputs.snap }}
