name: Snap Publish

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      SNAPCRAFT_STORE_CREDENTIALS:
        required: true

jobs:
  publish-snap:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Downloads locally built snap artifact
        uses: actions/download-artifact@v6
        id: download
        with:
          name: snap

      - name: Determine snap file name
        id: find-snap
        run: |
          SNAP_FILE=$(ls *.snap)
          echo "Found snap file: $SNAP_FILE"
          echo "snap_file=${SNAP_FILE}" >>$GITHUB_OUTPUT

      - name: Publish snap
        uses: canonical/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40 # v1.2.0
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.find-snap.outputs.snap_file }}
          release: 0.4/edge
