name: UI Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ui-lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: use npm
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm install --prefix ui

      - name: Run format check
        run: |
          npm run format:check --prefix ui

      - name: Run lint check
        run: |
          npm run lint --prefix ui
