name: UI Lint

on:
  workflow_call:

jobs:
  ui-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: use npm
        uses: actions/setup-node@v4

      - name: Run npm format check
        run: |
          npx prettier -c src/
