#!/bin/sh -e

cp "$SNAP/core.yaml" "$SNAP_COMMON/core.yaml"
mkdir "$SNAP_COMMON/data"

openssl req -newkey rsa:2048 -nodes -keyout $SNAP_COMMON/key.pem -x509 -days 1 -out $SNAP_COMMON/cert.pem -subj "/CN=core.ella.com"
